'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'src','13_Alpha71AggregateContract.js'),'utf8');
const context={console,Date,JSON,Math,Number,String,Object,Array,RegExp,Error,isFinite,AKORT:{Release:{version:'4.0.0-alpha.6.2.4'}}};vm.createContext(context);vm.runInContext(source,context,{filename:'13_Alpha71AggregateContract.js'});const C=context.AKORT.AggregateContract;
function assert(x,m){if(!x)throw new Error(m);}function equal(a,b,m){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error((m||'diff')+`: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);}function throwsCode(fn,c){try{fn();}catch(e){assert(e.code===c,`Expected ${c}, got ${e.code}: ${e.message}`);return;}throw new Error(`Expected ${c}`);}const tests=[];function test(n,f){tests.push({n,f});}
function frontier(freq='weekly',dataset='D',periods=['2026-01-04']){return C.buildFrontier('F',periods.map(period_start=>({frequency:freq,dataset_code:dataset,source_series_scope:'ALL',period_start})));}function opts(f){return{frontier:f,frontier_snapshot_id:f.snapshot_id,frontier_hash:f.hash,weight_snapshot_id:'W',membership_snapshot_id:'M',created_at:'2026-07-16T12:00:00Z'};}function fixtureSource(o={}){return Object.assign({load_id:'L',operation_id:'O',reason_code:'R',dataset_code:'D',series_id:'S',category_id:'C',frequency:'weekly',source_kind:'price_level',value_type:'V',index_type:'',period:'2026-01-04'},o);}
test('metadata remains candidate on accepted runtime',()=>{assert(C.Version==='4.0-aggregate-contract-2');assert(C.statusSummary().accepted_runtime_release==='4.0.0-alpha.6.2.4');assert(C.statusSummary().acceptance_status.includes('NO_GO'));});
test('index and frequency validation',()=>{equal(C.canonicalIndexTypes('weekly','','price_level'),['wow','yoy','december']);equal(C.canonicalIndexTypes('monthly','','price_level'),['mom','yoy','december']);throwsCode(()=>C.canonicalIndexTypes('quarterly','','price_level'),'AGG_FREQUENCY_INVALID');});
test('stable keys',()=>{const b={dataset_code:'D',frequency:'weekly',aggregate_level:'basket',aggregate_subject_id:'B',value_type:'V',index_type:'wow',calculation_method:'SUM',weight_rule_id:'W',membership_rule_id:'M'};assert(C.aggregateSeriesKey({...b,period_start:'2026-01-04',aggregate_name:'A'})===C.aggregateSeriesKey({...b,period_start:'2026-01-11',aggregate_name:'B'}));assert(C.aggregateRowKey({...b,period_start:'2026-01-04'})!==C.aggregateRowKey({...b,period_start:'2026-01-11'}));});
test('frontier required',()=>{const f=frontier();throwsCode(()=>C.buildImpactPlan([fixtureSource()],{frontier_snapshot_id:'F',frontier_hash:f.hash,weight_snapshot_id:'W',membership_snapshot_id:'M',created_at:'X'}),'AGG_FRONTIER_REQUIRED');});
test('frontier snapshot hash and count guards',()=>{const f=frontier();throwsCode(()=>C.validateFrontier(f,'X',f.hash),'AGG_FRONTIER_SNAPSHOT_MISMATCH');const a=JSON.parse(JSON.stringify(f));a.keys[C.frontierKey('weekly','D','ALL','2099-01-04')]=true;throwsCode(()=>C.validateFrontier(a,'F',f.hash),'AGG_FRONTIER_COUNT_MISMATCH');const b=JSON.parse(JSON.stringify(f));b.hash='bad';throwsCode(()=>C.validateFrontier(b,'F',f.hash),'AGG_FRONTIER_HASH_INVALID');});
test('future period explicitly blocked',()=>{const f=frontier('weekly','D',['2026-01-04']),p=C.buildImpactPlan([fixtureSource({candidate_periods:['2026-01-04','2099-01-04']})],opts(f));assert(p.summary.planned===3&&p.summary.blocked_contract===3);assert(p.items.filter(x=>x.status==='BLOCKED_CONTRACT').every(x=>x.contract_code==='AGG_FRONTIER_PERIOD_NOT_ALLOWED'));});
test('deterministic impact id and timestamp',()=>{const f=frontier(),a=C.buildImpactPlan([fixtureSource()],opts(f)).items[0],b=C.buildImpactPlan([fixtureSource()],opts(f)).items[0];assert(a.impact_id===b.impact_id&&a.impact_id.startsWith('AGG_IMPACT_'));assert(a.created_at);throwsCode(()=>C.buildImpactPlan([fixtureSource()],{...opts(f),created_at:''}),'AGG_CREATED_AT_MISSING');});
test('weekly and monthly dependencies',()=>{equal(C.dependencyCandidates('weekly','2026-01-04','wow'),['2026-01-04','2026-01-11']);equal(C.dependencyCandidates('monthly','2026-01','mom'),['2026-01','2026-02']);equal(C.dependencyCandidates('monthly','2025-12','yoy'),['2025-12','2026-12']);equal(C.dependencyCandidates('monthly','2025-12','december',['2026-01','2026-02','2027-01']),['2025-12','2026-01','2026-02']);});
test('versioned rules exact date and conflict',()=>{const r=[{weight_rule_id:'A',weight_version:'1',scope:'S',category_id:'C',effective_from:'2026-01-01',effective_to:'2026-06-14',status:'ACTIVE'},{weight_rule_id:'B',weight_version:'2',scope:'S',category_id:'C',effective_from:'2026-06-15',effective_to:'',status:'ACTIVE'}];assert(C.resolveVersionedRule(r,{category_id:'C',scope:'S',period:'2026-06-14'}).rule.weight_rule_id==='A');assert(C.resolveVersionedRule(r,{category_id:'C',scope:'S',period:'2026-06-15'}).rule.weight_rule_id==='B');throwsCode(()=>C.resolveVersionedRule(r.concat([{weight_rule_id:'C',weight_version:'3',scope:'S',category_id:'C',effective_from:'2026-06-15',status:'ACTIVE'}]),{category_id:'C',scope:'S',period:'2026-06-20'}),'CONTRACT_CONFLICT');});
test('value states',()=>{equal(C.classifyValue(null),{state:'MISSING',value:null});equal(C.classifyValue(0),{state:'ZERO',value:0});equal(C.classifyValue('x'),{state:'INVALID',value:null});equal(C.classifyValue(100,{notApplicable:true}),{state:'NOT_APPLICABLE',value:null});});
test('weighted average excludes N/A',()=>{const r=C.weightedAverage([{weight:1,value:100,notApplicable:true},{weight:1,value:50}],{allow_partial:false});assert(r.status==='READY'&&r.value===50&&r.coverage.coverage_status==='COMPLETE'&&r.coverage.not_applicable_members_count===1&&r.coverage.expected_members_count===1);});
test('markup excludes N/A',()=>{const r=C.aggregateMarkup([{weight:1,purchase:100,retail:200,notApplicable:true},{weight:1,purchase:100,retail:150}],0,{allow_partial:false});assert(r.status==='READY'&&r.aggregate_value===50&&r.coverage.coverage_status==='COMPLETE'&&r.coverage.not_applicable_members_count===1);});
test('all N/A has explicit state',()=>{const r=C.weightedAverage([{weight:1,value:100,notApplicable:true}],{});assert(r.status==='NOT_APPLICABLE'&&r.value===null&&r.coverage.coverage_status==='NOT_APPLICABLE');});
test('zero base blocked',()=>{assert(C.percentChange(120,0).status==='INVALID_BASE_ZERO');});
test('Borshch and one-to-many',()=>{const rows=[1,2,3,4,5].map(i=>({aggregate_subject_id:C.BorshchAggregateId,membership_version:C.BorshchMembershipVersion,category_id:`C${i}`,include_flag:1}));assert(C.validateMembershipSnapshot(rows,{aggregate_subject_id:C.BorshchAggregateId,membership_version:C.BorshchMembershipVersion,expected_count:5}).active_members_count===5);const one=[{aggregate_subject_id:'A',membership_version:'V',category_id:'C',include_flag:1},{aggregate_subject_id:'B',membership_version:'V',category_id:'C',include_flag:1}];assert(C.validateMembershipSnapshot(one,{aggregate_subject_id:'A',membership_version:'V',expected_count:1}).active_members_count===1);assert(C.validateMembershipSnapshot(one,{aggregate_subject_id:'B',membership_version:'V',expected_count:1}).active_members_count===1);});
test('invalid frequency not silent',()=>{const f=frontier();throwsCode(()=>C.buildImpactPlan([fixtureSource({frequency:'quarterly',period:'2026-Q1'})],opts(f)),'AGG_FREQUENCY_INVALID');});
test('industry explicitly skipped',()=>{const f=frontier(),p=C.buildImpactPlan([fixtureSource({load_id:'INDI',frequency:'industry',source_kind:'industry'})],opts(f));assert(p.items.length===0&&p.summary.skipped_not_applicable===1&&p.summary.blocked_contract===0);});
test('middle value changes full fingerprint',()=>{const h=['a','b'],a=[[1,2],[3,4],[5,6]],b=[[1,2],[3,999],[5,6]];assert(C.fingerprintRows(a,h)!==C.fingerprintRows(b,h));});
let failed=0;for(const x of tests){try{x.f();console.log(`PASS ${x.n}`);}catch(e){failed++;console.error(`FAIL ${x.n}: ${e.stack||e}`);}}console.log(JSON.stringify({suite:'alpha71_contract_static_r2',total:tests.length,failed},null,2));process.exitCode=failed?1:0;
