var AKORT = typeof AKORT !== 'undefined' ? AKORT : {};
AKORT.Alpha6Tests = (function(){
  function test_(id,fn){try{return{id:id,status:'PASS',data:fn(),error:null};}catch(e){return{id:id,status:'FAIL',data:null,error:String(e.message||e)};}}
  function approx_(a,b,t){if(Math.abs(Number(a)-Number(b))>Number(t||1e-6))throw new Error('Expected '+b+', got '+a);}
  function runSmokeTest(){return AKORT.Core.safeRun('ALPHA6_SMOKE_TEST',function(){AKORT.EnvironmentGuard.assertDev();var T=AKORT.IncrementalPublish.Test,tests=[];
    tests.push(test_('publish_contract',function(){var s=AKORT.IncrementalPublish.statusSummary();if(s.publishSchemaVersion!=='4.0-publish-1'||s.dependencySchemaVersion!=='4.0-dependency-1')throw new Error('Unexpected schema version');['PUBLISH_IMPACT','PUBLISH_RUNS','PUBLISH_RECONCILIATION'].forEach(function(n){if(!s.serviceTables[n])throw new Error('Missing '+n);});return s;}));
    tests.push(test_('weekly_dependency_closure',function(){var p=T.weeklyDependentPeriods(new Date(2025,11,28,12));if(p.indexOf('2025-12-28')<0||p.indexOf('2026-01-04')<0)throw new Error('Weekly direct dependency missing');if(p.length<54)throw new Error('December must invalidate next-year weeks');return{count:p.length,first:p.slice(0,4)};}));
    tests.push(test_('monthly_dependency_closure',function(){var p=T.monthlyDependentPeriods(new Date(2025,11,1,12));if(p.indexOf('2025-12')<0||p.indexOf('2026-01')<0||p.indexOf('2026-12')<0)throw new Error('Monthly December closure incomplete');return p;}));
    tests.push(test_('weekly_wow_yoy_december_ma4',function(){var rows=[],dates=[new Date(2024,11,29,12),new Date(2025,0,5,12),new Date(2025,0,12,12),new Date(2025,0,19,12),new Date(2025,0,26,12),new Date(2026,0,25,12)],vals=[100,101,102,103,104,120];dates.forEach(function(d,i){var iso=(function(){var x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);var y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return{year:x.getUTCFullYear(),week:Math.ceil((((x-y)/86400000)+1)/7)};})();rows.push({series_id:'S',dataset_code:'D',category_id:'C',value_type:'розница',series_type:'OFFICIAL_WEEKLY',observation_date:d,year:d.getFullYear(),month:d.getMonth()+1,iso_year:iso.year,iso_week:iso.week,current_value:vals[i]});});T.weeklyDynamics(rows);var r=rows[4];approx_(r.wow_abs,1);approx_(r.moving_average_4w,102.5);approx_(r.december_pct,4);return r;}));
    tests.push(test_('monthly_mom_yoy_december',function(){var rows=[{series_id:'M',dataset_code:'D',category_id:'C',value_type:'розница',series_type:'OFFICIAL_MONTHLY',month_start:new Date(2024,11,1,12),year:2024,month:12,current_value:100},{series_id:'M',dataset_code:'D',category_id:'C',value_type:'розница',series_type:'OFFICIAL_MONTHLY',month_start:new Date(2025,0,1,12),year:2025,month:1,current_value:110},{series_id:'M',dataset_code:'D',category_id:'C',value_type:'розница',series_type:'OFFICIAL_MONTHLY',month_start:new Date(2026,0,1,12),year:2026,month:1,current_value:121}];T.monthlyDynamics(rows);approx_(rows[1].mom_pct,10);approx_(rows[1].december_pct,10);approx_(rows[2].yoy_pct,10);return rows;}));
    tests.push(test_('industry_ytd_semantics',function(){var rows=[{series_id:'I',frequency:'monthly',year:2025,month:1,current_value:100,_periodBasis:'cumulative_ytd',_metricType:'level',_comparisonDate:new Date(2025,0,1,12)},{series_id:'I',frequency:'monthly',year:2026,month:1,current_value:120,_periodBasis:'cumulative_ytd',_metricType:'level',_comparisonDate:new Date(2026,0,1,12)}];T.industryDynamics(rows);if(rows[1].previous_period_value!==''&&rows[1].previous_period_value!==undefined)throw new Error('YTD must not calculate previous-period change');approx_(rows[1].yoy_pct,20);return rows[1];}));
    tests.push(test_('revision_impact_expansion',function(){var x=T.expandAffected([{frequency:'weekly',datasetCode:'AKORT_WEEKLY',categoryId:'C',valueType:'розница',indexType:'',period:'2026-06-28'}]);if(!x.weekly.length||!x.monthly.length||!x.aggregates.length)throw new Error('AKORT revision did not propagate to markup, derived monthly and aggregates');return{weekly:x.weekly.length,monthly:x.monthly.length,aggregates:x.aggregates.length};}));
    tests.push(test_('latest_points_by_economic_series',function(){var rows=[{series_id:'A',observation_date:new Date(2026,0,1,12)},{series_id:'A',observation_date:new Date(2026,0,8,12)},{series_id:'B',observation_date:new Date(2026,0,1,12)}];T.setLatestPrices(rows,'observation_date');if(rows[0].is_latest_period!==0||rows[1].is_latest_period!==1||rows[2].is_latest_period!==1)throw new Error('Latest flags are not series-specific');return rows;}));
    tests.push(test_('historical_load_replay_revision_and_reversal',function(){var rows=[{dataset_code:'D',category_id:'C',value_type:'розница',index_type:'',observation_date:'2026-01-04',value:100,version_no:1,loaded_at:'2026-01-05T00:00:00Z',load_id:'L1'},{dataset_code:'D',category_id:'C',value_type:'розница',index_type:'',observation_date:'2026-01-04',value:110,version_no:2,loaded_at:'2026-02-01T00:00:00Z',load_id:'L2'}],initial=T.selectReplayLatest('RAW_PRICES_WEEKLY',rows,{L1:true},{}),revised=T.selectReplayLatest('RAW_PRICES_WEEKLY',rows,{L1:true,L2:true},{}),reversed=T.selectReplayLatest('RAW_PRICES_WEEKLY',rows,{L1:true,L2:true},{L2:true});if(initial.length!==1||Number(initial[0].value)!==100)throw new Error('Initial replay state failed');if(revised.length!==1||Number(revised[0].value)!==110)throw new Error('Revision replay state failed');if(reversed.length!==1||Number(reversed[0].value)!==100)throw new Error('Reversal replay state failed');return{initial:initial[0].value,revised:revised[0].value,reversed:reversed[0].value};}));
    tests.push(test_('aggregate_latest_key',function(){var rows=[{dataset_code:'D',frequency:'weekly',aggregate_level:'category',category_id:'A',aggregate_name:'Вклад категории',value_type:'розница',index_type:'wow',weight_source:'W',period_start:new Date(2026,0,1,12)},{dataset_code:'D',frequency:'weekly',aggregate_level:'category',category_id:'B',aggregate_name:'Вклад категории',value_type:'розница',index_type:'wow',weight_source:'W',period_start:new Date(2026,0,8,12)}];T.setLatestAggregates(rows);if(rows[0].is_latest_period!==1||rows[1].is_latest_period!==1)throw new Error('Different category series competed for latest');return rows;}));
    tests.push(test_('baseline_unchanged',function(){var c=AKORT.Config.load({includeSystemSettings:false}),d=SpreadsheetApp.openById(c.resources.dwhSpreadsheetId),p=SpreadsheetApp.openById(c.resources.publishSpreadsheetId),a={rawWeeklyRows:d.getSheetByName('RAW_PRICES_WEEKLY').getLastRow()-1,rawMonthlyRows:d.getSheetByName('RAW_PRICES_MONTHLY').getLastRow()-1,rawIndustryRows:d.getSheetByName('RAW_INDUSTRY').getLastRow()-1,publishWeeklyRows:p.getSheetByName('PUBLISH_PRICES_WEEKLY').getLastRow()-1,publishMonthlyRows:p.getSheetByName('PUBLISH_PRICES_MONTHLY').getLastRow()-1,publishIndustryRows:p.getSheetByName('PUBLISH_INDUSTRY').getLastRow()-1,publishAggregateRows:p.getSheetByName('PUBLISH_PRICE_AGGREGATES').getLastRow()-1},e=c.baselinePhysicalExpected;Object.keys(e).forEach(function(k){if(Number(a[k])!==Number(e[k]))throw new Error(k+' changed: '+a[k]+' vs '+e[k]);});return a;}));
    tests.push(test_('reconciliation_entrypoints_ready',function(){return{phases:['full build','sequential load impact replay','verified baseline comparison'],status:AKORT.IncrementalPublish.reconciliationStatus().status};}));
    var ok=tests.every(function(x){return x.status==='PASS';});return ok?AKORT.Result.success('Alpha.6 Incremental Publish smoke test passed.',{tests:tests,status:AKORT.IncrementalPublish.statusSummary()}):AKORT.Result.failure('ALPHA6_SMOKE_TEST_FAILED','One or more alpha.6 checks failed.',{tests:tests});},{lock:true,persistLogs:true});}
  return{runSmokeTest:runSmokeTest};
})();
