var AKORT = typeof AKORT !== 'undefined' ? AKORT : {};

/** Read-only candidate suite for Alpha.7.1 Aggregate Contract. */
AKORT.Alpha71ContractTests = (function () {
  function test_(id, fn) { try { return {id:id,status:'PASS',data:fn(),error:null}; } catch (error) { return {id:id,status:'FAIL',data:null,error:{name:String(error&&error.name||''),code:String(error&&error.code||''),message:String(error&&error.message||error||''),details:error&&error.details?error.details:null,stack:String(error&&error.stack||'')}}; } }
  function stable_(value) { if (Array.isArray(value)) return value.map(stable_); if (value&&typeof value==='object'&&!(value instanceof Date)) { var out={}; Object.keys(value).sort().forEach(function(k){out[k]=stable_(value[k]);}); return out; } return value; }
  function equal_(a,b,m){var x=JSON.stringify(stable_(a)),y=JSON.stringify(stable_(b));if(x!==y)throw new Error((m||'Values differ')+': expected '+y+', got '+x);}
  function approx_(a,b,t,m){if(Math.abs(Number(a)-Number(b))>Number(t||1e-6))throw new Error((m||'Values differ')+': expected '+b+', got '+a);}
  function throwsCode_(fn,code){try{fn();}catch(e){if(String(e&&e.code||'')!==code)throw new Error('Expected '+code+', got '+String(e&&e.code||'')+': '+String(e&&e.message||e));return code;}throw new Error('Expected '+code+' but no error was thrown.');}
  function frontier_(C, frequency, dataset, periods){return C.buildFrontier('FRONTIER_TEST',(periods||[]).map(function(p){return{frequency:frequency,dataset_code:dataset,source_series_scope:'ALL',period_start:p};}));}
  function options_(frontier){return{frontier:frontier,frontier_snapshot_id:frontier.snapshot_id,frontier_hash:frontier.hash,weight_snapshot_id:'WEIGHTS_2026_V1',membership_snapshot_id:'MEMBERSHIP_2026_V1',created_at:'2026-07-16T12:00:00.000Z'};}
  function realPreview_(){var r=AKORT.IncrementalPublish.reconciliationStatus(),root=r&&(r.data||r.details)||r||{},found=null;function walk(v,d){if(found||d>8||v===null||v===undefined)return;if(Array.isArray(v)){if(v.some(function(x){return x&&typeof x==='object'&&(x.loadId||x.load_id);}))found=v;else v.forEach(function(x){walk(x,d+1);});return;}if(typeof v==='object'){if(Array.isArray(v.aggregateImpactPreview))found=v.aggregateImpactPreview;else Object.keys(v).forEach(function(k){walk(v[k],d+1);});}}walk(root,0);if(!found)throw new Error('Accepted reconciliation aggregateImpactPreview evidence is unavailable.');return found;}
  function previewByLoad_(rows,id){return(rows||[]).filter(function(x){return String(x.loadId||x.load_id||x.sourceProfile||x.source_profile||'')===id;})[0]||null;}
  function previewCount_(row){return Number(row&&(row.comboRows||row.combo_rows||row.aggregateComboCount||row.aggregate_combo_count||row.combinations||row.rows||0));}

  function runAll(){return AKORT.Core.safeRun('ALPHA71_AGGREGATE_CONTRACT_TESTS_R2',function(){
    AKORT.EnvironmentGuard.assertDev(); var C=AKORT.AggregateContract,T=AKORT.IncrementalPublish.Test,tests=[],before=C.inventory(),baseline=C.baselineInventory();
    tests.push(test_('candidate_metadata_does_not_claim_release_acceptance',function(){if(AKORT.Release.version!=='4.0.0-alpha.6.2.4')throw new Error('Runtime release changed before Alpha.7.1 acceptance.');var s=C.statusSummary();if(s.contract_version!=='4.0-aggregate-contract-2'||s.acceptance_status.indexOf('NO_GO')<0)throw new Error('Candidate status is not explicit.');return s;}));
    tests.push(test_('full_sheet_matches_configured_verified_baseline',function(){var c=C.compareInventory(before,baseline);if(!c.equal)throw new Error('DEV aggregate sheet differs from configured verified baseline: '+JSON.stringify(c.differing_fields));return c;}));
    tests.push(test_('inventory_schema_counts_and_index_types',function(){equal_(before.headers,C.Headers);if(before.rows!==C.ExpectedInventory.rows||before.columns!==C.Headers.length)throw new Error('Inventory shape changed.');equal_(before.frequency,C.ExpectedInventory.frequency);equal_(before.aggregate_level,C.ExpectedInventory.aggregateLevel);equal_(before.index_type,C.ExpectedInventory.indexType);if(before.blank_index_types||before.invalid_index_types)throw new Error('Blank or invalid index_type found.');if(!before.data_hash||before.data_hash.length!==64)throw new Error('Full-sheet SHA-256 is missing.');return{rows:before.rows,hash:before.data_hash};}));
    tests.push(test_('frequency_and_index_type_validation',function(){equal_(C.canonicalIndexTypes('weekly','','price_level'),['wow','yoy','december']);equal_(C.canonicalIndexTypes('monthly','','price_level'),['mom','yoy','december']);throwsCode_(function(){C.canonicalIndexTypes('weekly','mom','official_index');},'AGG_INDEX_TYPE_INVALID');throwsCode_(function(){C.canonicalIndexTypes('quarterly','','price_level');},'AGG_FREQUENCY_INVALID');return true;}));
    tests.push(test_('stable_series_and_row_keys',function(){var b={dataset_code:'D',frequency:'weekly',aggregate_level:'basket',aggregate_subject_id:'B',value_type:'V',index_type:'wow',calculation_method:'SUM',weight_rule_id:'W',membership_rule_id:'M'},a=C.aggregateSeriesKey(b),z=C.aggregateSeriesKey(Object.assign({},b,{aggregate_name:'Renamed',period_start:'2026-01-04'}));if(a!==z)throw new Error('Series key depends on display or period.');if(C.aggregateRowKey(Object.assign({},b,{period_start:'2026-01-04'}))===C.aggregateRowKey(Object.assign({},b,{period_start:'2026-01-11'})))throw new Error('Row key ignores period.');return a;}));
    tests.push(test_('frontier_is_materialized_and_hash_guarded',function(){var f=frontier_(C,'weekly','D',['2026-01-04']);throwsCode_(function(){C.buildImpactPlan([],{frontier_snapshot_id:f.snapshot_id,frontier_hash:f.hash,weight_snapshot_id:'W',membership_snapshot_id:'M',created_at:'X'});},'AGG_FRONTIER_REQUIRED');throwsCode_(function(){C.validateFrontier(f,'OTHER',f.hash);},'AGG_FRONTIER_SNAPSHOT_MISMATCH');var tampered=JSON.parse(JSON.stringify(f));tampered.keys[C.frontierKey('weekly','D','ALL','2099-01-04')]=true;throwsCode_(function(){C.validateFrontier(tampered,f.snapshot_id,f.hash);},'AGG_FRONTIER_COUNT_MISMATCH');return f;}));
    tests.push(test_('outside_frontier_is_explicitly_blocked',function(){var f=frontier_(C,'weekly','D',['2026-01-04']),plan=C.buildImpactPlan([{load_id:'L',operation_id:'O',reason_code:'R',dataset_code:'D',series_id:'S',category_id:'C',frequency:'weekly',source_kind:'price_level',value_type:'V',index_type:'',period:'2026-01-04',candidate_periods:['2026-01-04','2099-01-04']}],options_(f));if(plan.summary.planned!==3||plan.summary.blocked_contract!==3)throw new Error('Planned/blocked split is incorrect.');var blocked=plan.items.filter(function(x){return x.status==='BLOCKED_CONTRACT';});if(blocked.length!==3||blocked.some(function(x){return x.contract_code!=='AGG_FRONTIER_PERIOD_NOT_ALLOWED';}))throw new Error('Future items were not explicitly blocked.');return plan.summary;}));
    tests.push(test_('impact_ids_and_created_at_are_deterministic_and_required',function(){var f=frontier_(C,'weekly','D',['2026-01-04']),o=options_(f),source=[{load_id:'L',operation_id:'O',reason_code:'R',dataset_code:'D',series_id:'S',category_id:'C',frequency:'weekly',source_kind:'official_index',value_type:'V',index_type:'wow',period:'2026-01-04'}],a=C.buildImpactPlan(source,o).items[0],b=C.buildImpactPlan(source,o).items[0];if(!a.impact_id||a.impact_id!==b.impact_id||!a.created_at)throw new Error('Impact identity/timestamp missing or nondeterministic.');var bad=Object.assign({},o,{created_at:''});throwsCode_(function(){C.buildImpactPlan(source,bad);},'AGG_CREATED_AT_MISSING');return{impact_id:a.impact_id,created_at:a.created_at};}));
    tests.push(test_('weekly_and_monthly_dependency_windows',function(){equal_(C.dependencyCandidates('weekly','2026-01-04','wow'),['2026-01-04','2026-01-11']);equal_(C.dependencyCandidates('monthly','2026-01','mom'),['2026-01','2026-02']);equal_(C.dependencyCandidates('monthly','2025-12','yoy'),['2025-12','2026-12']);var m=T.monthlyDependentPeriods(new Date(2025,11,1,12));if(m.indexOf('2026-01')<0||m.indexOf('2026-12')<0)throw new Error('Production monthly dependency closure is incomplete.');return m;}));
    tests.push(test_('december_existing_periods_only',function(){equal_(C.dependencyCandidates('monthly','2025-12','december',['2026-01','2026-02','2027-01']),['2025-12','2026-01','2026-02']);return true;}));
    tests.push(test_('versioned_rule_exact_dates_and_conflict',function(){var rules=[{weight_rule_id:'A',weight_version:'1',scope:'S',category_id:'C',effective_from:'2026-01-01',effective_to:'2026-06-14',status:'ACTIVE'},{weight_rule_id:'B',weight_version:'2',scope:'S',category_id:'C',effective_from:'2026-06-15',effective_to:'',status:'ACTIVE'}];if(C.resolveVersionedRule(rules,{category_id:'C',scope:'S',period:'2026-06-14'}).rule.weight_rule_id!=='A'||C.resolveVersionedRule(rules,{category_id:'C',scope:'S',period:'2026-06-15'}).rule.weight_rule_id!=='B')throw new Error('Exact effective date failed.');var conflict=rules.concat([{weight_rule_id:'C',weight_version:'3',scope:'S',category_id:'C',effective_from:'2026-06-15',effective_to:'',status:'ACTIVE'}]);throwsCode_(function(){C.resolveVersionedRule(conflict,{category_id:'C',scope:'S',period:'2026-06-20'});},'CONTRACT_CONFLICT');return true;}));
    tests.push(test_('missing_zero_invalid_not_applicable_semantics',function(){equal_(C.classifyValue(null),{state:'MISSING',value:null});equal_(C.classifyValue(0),{state:'ZERO',value:0});equal_(C.classifyValue('x'),{state:'INVALID',value:null});equal_(C.classifyValue(100,{notApplicable:true}),{state:'NOT_APPLICABLE',value:null});return true;}));
    tests.push(test_('weighted_average_excludes_not_applicable',function(){var r=C.weightedAverage([{weight:1,value:100,notApplicable:true},{weight:1,value:50}],{allow_partial:false});if(r.status!=='READY'||r.value!==50||r.coverage.coverage_status!=='COMPLETE'||r.coverage.not_applicable_members_count!==1||r.coverage.expected_members_count!==1)throw new Error('NOT_APPLICABLE member affected numerator, denominator, or coverage.');return r;}));
    tests.push(test_('aggregate_markup_excludes_not_applicable',function(){var r=C.aggregateMarkup([{weight:1,purchase:100,retail:200,notApplicable:true},{weight:1,purchase:100,retail:150}],0,{allow_partial:false});if(r.status!=='READY'||r.aggregate_value!==50||r.coverage.coverage_status!=='COMPLETE'||r.coverage.not_applicable_members_count!==1)throw new Error('NOT_APPLICABLE markup member was included.');return r;}));
    tests.push(test_('zero_base_percent_change_is_blocked',function(){var r=C.percentChange(120,0);if(r.status!=='INVALID_BASE_ZERO'||r.value!==null)throw new Error('Zero base was accepted.');return r;}));
    tests.push(test_('five_member_borshch_and_one_to_many_membership',function(){var rows=[1,2,3,4,5].map(function(i){return{aggregate_subject_id:C.BorshchAggregateId,membership_version:C.BorshchMembershipVersion,category_id:'C'+i,include_flag:1};});if(C.validateMembershipSnapshot(rows,{aggregate_subject_id:C.BorshchAggregateId,membership_version:C.BorshchMembershipVersion,expected_count:5}).active_members_count!==5)throw new Error('Borshch membership invalid.');var oneToMany=[{aggregate_subject_id:'A',membership_version:'V',category_id:'C',include_flag:1},{aggregate_subject_id:'B',membership_version:'V',category_id:'C',include_flag:1}];if(C.validateMembershipSnapshot(oneToMany,{aggregate_subject_id:'A',membership_version:'V',expected_count:1}).active_members_count!==1||C.validateMembershipSnapshot(oneToMany,{aggregate_subject_id:'B',membership_version:'V',expected_count:1}).active_members_count!==1)throw new Error('One-to-many was treated as duplicate.');return true;}));
    tests.push(test_('invalid_non_industry_frequency_is_not_silently_skipped',function(){var f=frontier_(C,'weekly','D',['2026-01-04']);throwsCode_(function(){C.buildImpactPlan([{load_id:'L',operation_id:'O',reason_code:'R',dataset_code:'D',series_id:'S',category_id:'C',frequency:'quarterly',source_kind:'price_level',value_type:'V',period:'2026-Q1'}],options_(f));},'AGG_FREQUENCY_INVALID');return true;}));
    tests.push(test_('real_accepted_AWI_and_INDI_evidence',function(){var rows=realPreview_(),awi=previewByLoad_(rows,'AWI'),indi=previewByLoad_(rows,'INDI');if(!awi||!indi)throw new Error('Real AWI/INDI reconciliation evidence not found.');if(previewCount_(awi)<=0)throw new Error('Real AWI evidence has zero aggregate impact.');if(previewCount_(indi)!==0)throw new Error('Real INDI evidence has non-zero aggregate impact.');return{awi:previewCount_(awi),indi:previewCount_(indi)};}));
    tests.push(test_('physical_aggregate_execution_remains_disabled',function(){var s=AKORT.IncrementalPublish.runtimeSettings();if(s.aggregateExecutionEnabled!==false||s.aggregateExecutionStatus!=='DEFERRED_TO_ALPHA7')throw new Error('Physical aggregate execution enabled.');return s;}));
    var after=C.inventory();
    tests.push(test_('suite_did_not_modify_any_aggregate_cell',function(){if(before.data_hash!==after.data_hash||before.fingerprint!==after.fingerprint)throw new Error('Full aggregate sheet hash changed during suite.');return{before:before.data_hash,after:after.data_hash};}));
    var failed=tests.filter(function(x){return x.status!=='PASS';}),report={candidate_release:C.Release,accepted_runtime_release:AKORT.Release.version,contract_version:C.Version,acceptance_status:'PRE_ACCEPTANCE',mode:'READ_ONLY',executed_at:AKORT.Core.now(),total:tests.length,passed:tests.length-failed.length,failed:failed.length,tests:tests,inventory:{rows:before.rows,data_hash:before.data_hash,baseline_hash:baseline.data_hash}};
    return failed.length?AKORT.Result.failure('ALPHA71_CONTRACT_TESTS_FAILED','Alpha.7.1 candidate contract suite failed.',report):AKORT.Result.success('Alpha.7.1 candidate contract suite passed; compatibility tests are still required before release acceptance.',report);
  },{lock:true,persistLogs:true});}
  return Object.freeze({runAll:runAll});
})();

function AKORT_alpha71RunContractTests(){var r=AKORT.Alpha71ContractTests.runAll();console.log(JSON.stringify(r,null,2));return r;}
function AKORT_alpha71ContractStatus(){var r=AKORT.Result.success('Alpha.7.1 aggregate contract candidate status loaded.',AKORT.AggregateContract.statusSummary());console.log(JSON.stringify(r,null,2));return r;}
function AKORT_alpha71AggregateInventory(){return AKORT.Core.safeRun('ALPHA71_AGGREGATE_INVENTORY',function(){AKORT.EnvironmentGuard.assertDev();var r=AKORT.Result.success('Current and configured baseline aggregate inventories loaded.',{current:AKORT.AggregateContract.inventory(),baseline:AKORT.AggregateContract.baselineInventory()});console.log(JSON.stringify(r,null,2));return r;},{lock:true,persistLogs:true});}
