var AKORT = typeof AKORT !== 'undefined' ? AKORT : {};

/** Alpha.7.2 pure/static and read-only live acceptance tests. */
AKORT.Alpha72CalculatorTests = (function () {
  function stable_(value) { if (Array.isArray(value)) return value.map(stable_); if (value && typeof value === 'object' && !(value instanceof Date)) { var out={}; Object.keys(value).sort().forEach(function(k){out[k]=stable_(value[k]);}); return out; } return value; }
  function equal_(a,b,message) { var x=JSON.stringify(stable_(a)),y=JSON.stringify(stable_(b)); if(x!==y) throw new Error((message||'Values differ')+': expected '+y+', got '+x); }
  function assert_(condition,message) { if(!condition) throw new Error(message||'Assertion failed.'); }
  function approx_(actual,expected,tolerance,message) { if(Math.abs(Number(actual)-Number(expected))>Number(tolerance||1e-6)) throw new Error((message||'Values differ')+': expected '+expected+', got '+actual); }
  function test_(id,name,fn) { try { var data=fn(); if(data&&data.__skip===true) return{id:id,name:name,status:'SKIP',data:data.data||null,error:null}; return{id:id,name:name,status:'PASS',data:data===undefined?true:data,error:null}; } catch(error) { return{id:id,name:name,status:'FAIL',data:null,error:{name:String(error&&error.name||''),code:String(error&&error.code||''),message:String(error&&error.message||error||''),details:error&&error.details?error.details:null,stack:String(error&&error.stack||'')}}; } }
  function skip_(data){return{__skip:true,data:data||null};}
  function clone_(value){return JSON.parse(JSON.stringify(value));}
  function reverse_(rows){return (rows||[]).slice().reverse();}

  function price_(category,change,overrides){return Object.assign({dataset_code:'D',frequency:'weekly',series_id:'S_'+category,category_id:category,value_type:'price_index',index_type:'wow',period_start:'2026-01-11',current_value:100+Number(change||0),base_value:100,change_pp:change,unit:'percentage_point'},overrides||{});}
  function weight_(scope,category,value,overrides){return Object.assign({weight_rule_id:'WR1',weight_version:'1',weight_scope:scope,category_id:category,weight_value:value,effective_from:'2020-01-01',effective_to:'',status:'ACTIVE'},overrides||{});}
  function member_(subject,category,overrides){return Object.assign({membership_rule_id:'MR1',membership_version:'1',aggregate_subject_id:subject,category_id:category,allocation_factor:1,include_flag:1,effective_from:'2020-01-01',effective_to:'',status:'ACTIVE'},overrides||{});}
  function definition_(overrides){return Object.assign({dataset_code:'D',frequency:'weekly',aggregate_level:'group',aggregate_subject_id:'G1',aggregate_name:'Group 1',value_type:'price_index',index_type:'wow',calculation_method:'SUM_CONTRIBUTIONS',weight_rule_id:'WR1',membership_rule_id:'MR1',coverage_rule_id:'DEFAULT_COMPLETE_ONLY',output_unit:'percentage_point'},overrides||{});}
  function impact_(overrides){return Object.assign({load_id:'L1',operation_id:'O1',reason_code:'R',source_dataset_code:'D',source_series_id:'S_C1',source_category_id:'C1',source_period:'2026-01-11',frequency:'weekly',target_value_type:'price_index',target_index_type:'wow',target_aggregate_scope:'ALL_APPLICABLE',target_period:'2026-01-11',weight_snapshot_id:'W1',membership_snapshot_id:'M1',frontier_snapshot_id:'F1',status:'PLANNED',created_at:'2026-07-18T00:00:00.000Z'},overrides||{});}
  function request_(overrides){
    var base={contract_version:AKORT.AggregateContract.Version,calculation_id:'CALC_TEST',impact_items:[impact_()],price_inputs:[price_('C1',4),price_('C2',8)],aggregate_definitions:[definition_()],weight_snapshot:{snapshot_id:'W1',hash:'WEIGHT_HASH',rule_rows:[weight_('G1','C1',0.25),weight_('G1','C2',0.75)]},membership_snapshot:{snapshot_id:'M1',hash:'MEMBERSHIP_HASH',rule_rows:[member_('G1','C1'),member_('G1','C2')]},coverage_rules:[],base_inputs:[],options:{}};
    var source=overrides||{}; Object.keys(source).forEach(function(key){base[key]=source[key];}); return base;
  }
  function aggregateRow_(result,subject){return (result.rows||[]).filter(function(row){return row.row_type==='AGGREGATE_RESULT'&&(!subject||row.aggregate_subject_id===subject);})[0]||null;}
  function categoryRow_(result,category){return (result.rows||[]).filter(function(row){return row.row_type==='CATEGORY_CONTRIBUTION'&&row.category_id===category;})[0]||null;}
  function runBatch_(overrides){return AKORT.AggregateCalculator.calculateBatch(request_(overrides));}

  function runPure(options){
    var A=AKORT.AggregateCalculator,C=AKORT.AggregateContract,opts=options||{},tests=[];
    tests.push(test_('T72-001','Percent change positive',function(){var r=A.calculatePercentChange(110,100);assert_(r.status==='READY');approx_(r.value,10);return r;}));
    tests.push(test_('T72-002','Percent change negative',function(){var r=A.calculatePercentChange(90,100);assert_(r.status==='READY');approx_(r.value,-10);return r;}));
    tests.push(test_('T72-003','Zero current remains valid',function(){var r=A.calculatePercentChange(0,100);assert_(r.status==='READY');approx_(r.value,-100);return r;}));
    tests.push(test_('T72-004','Zero base is blocked',function(){var r=A.calculatePercentChange(100,0);assert_(r.status==='INVALID_BASE_ZERO'&&r.value===null);return r;}));
    tests.push(test_('T72-005','Category contribution formula',function(){var r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(definition_()),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'C1',category_value:104,change_pp:4,weight:0.25,allocation_factor:1}]});var row=r.rows[0];approx_(row.contribution_to_group_change_pp,1);return row;}));
    tests.push(test_('T72-006','Zero category change is applied',function(){var r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(definition_()),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'C1',category_value:100,change_pp:0,weight:0.25,allocation_factor:1}]});assert_(r.coverage.applied_members_count===1);approx_(r.rows[0].contribution_to_group_change_pp,0);return r.coverage;}));
    tests.push(test_('T72-007','Negative category change contribution',function(){var r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(definition_()),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'C1',category_value:96,change_pp:-4,weight:0.25,allocation_factor:1}]});approx_(r.rows[0].contribution_to_group_change_pp,-1);return r.rows[0];}));
    tests.push(test_('T72-008','Sum canonical contributions',function(){var r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(definition_()),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'A',change_pp:1.1,weight:1},{category_id:'B',change_pp:-0.4,weight:1},{category_id:'C',change_pp:0.3,weight:1}]});approx_(r.value,1);return r.value;}));
    tests.push(test_('T72-009','SUM_CONTRIBUTIONS does not renormalize',function(){var r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(definition_()),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'A',change_pp:10,weight:0.2},{category_id:'B',change_pp:null,change_state:'MISSING',weight:0.8}]});approx_(r.value,2);assert_(r.coverage.coverage_status==='PARTIAL'&&!r.coverage.publication_allowed);return r;}));
    tests.push(test_('T72-010','Scope-specific contribution fields',function(){var levels=['group','basket','total_cpi'],fields=['contribution_to_group_change_pp','contribution_to_basket_change_pp','contribution_to_total_cpi_pp'],out={};levels.forEach(function(level,i){var def=definition_({aggregate_level:level,aggregate_subject_id:level==='group'?'G1':(level==='basket'?'B1':'T1'),membership_rule_id:'MR1'}),r=A.calculateStandardAggregate({calculation_id:'X',impact_id:'I',combo_key:'K',definition:A.Test.normalizeDefinition(def),period_start:'2026-01-11',coverage_rule:{allow_partial:false},members:[{category_id:'C1',change_pp:4,weight:i+1}]});out[level]=r.rows[0];approx_(out[level][fields[i]],4*(i+1));});assert_(out.group.contribution_to_basket_change_pp===null&&out.basket.contribution_to_group_change_pp===null);return out;}));

    tests.push(test_('T72-011','Complete normalized weighted average',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:10,weight:1},{category_id:'B',value:20,weight:3}],coverage_rule:{allow_partial:false}});approx_(r.value,17.5);assert_(r.coverage.coverage_status==='COMPLETE');return r;}));
    tests.push(test_('T72-012','Partial weighted average not publishable',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:10,weight:1},{category_id:'B',value:null,value_state:'MISSING',weight:3}],coverage_rule:{allow_partial:false}});assert_(r.status==='PARTIAL_NOT_PUBLISHABLE'&&!r.coverage.publication_allowed);return r;}));
    tests.push(test_('T72-013','Explicit partial policy allows result',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:10,weight:1},{category_id:'B',value:null,value_state:'MISSING',weight:3}],coverage_rule:{allow_partial:true}});assert_(r.status==='READY'&&r.coverage.coverage_status==='PARTIAL'&&r.coverage.publication_allowed);return r;}));
    tests.push(test_('T72-014','Zero applied weight is blocked',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:null,value_state:'MISSING',weight:1}],coverage_rule:{allow_partial:false}});assert_(r.status==='BLOCKED_ZERO_APPLIED_WEIGHT');return r;}));
    tests.push(test_('T72-015','Invalid member blocks weighted average',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:'bad',weight:1}],coverage_rule:{allow_partial:false}});assert_(r.status==='BLOCKED_INVALID_MEMBER'&&r.coverage.coverage_status==='INVALID');return r;}));
    tests.push(test_('T72-016','NOT_APPLICABLE excluded from expectations',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:10,weight:1},{category_id:'B',value:null,value_state:'NOT_APPLICABLE',weight:100}],coverage_rule:{allow_partial:false}});assert_(r.coverage.expected_members_count===1&&r.coverage.expected_weight_sum===1);approx_(r.value,10);return r;}));

    tests.push(test_('T72-017','Markup uses weighted levels',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:100,retail:120,weight:1},{category_id:'B',purchase:200,retail:220,weight:1}],coverage_rule:{allow_partial:false}});approx_(r.weighted_purchase,150);approx_(r.weighted_retail,170);approx_(r.aggregate_value,13.333333);return r;}));
    tests.push(test_('T72-018','Markup is not average of category percentages',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:100,retail:120,weight:1},{category_id:'B',purchase:200,retail:220,weight:1}],coverage_rule:{allow_partial:false}});assert_(Math.abs(r.aggregate_value-15)>1);return r.aggregate_value;}));
    tests.push(test_('T72-019','Zero purchase blocks markup',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:0,retail:10,weight:1}],coverage_rule:{allow_partial:false}});assert_(r.status==='INVALID_BASE_ZERO');return r;}));
    tests.push(test_('T72-020','Missing price pair causes partial coverage',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:100,retail:120,weight:1},{category_id:'B',purchase:null,purchase_state:'MISSING',retail:220,weight:1}],coverage_rule:{allow_partial:false}});assert_(r.coverage.coverage_status==='PARTIAL'&&r.status==='PARTIAL_NOT_PUBLISHABLE');return r;}));
    tests.push(test_('T72-021','Applicability mismatch is invalid',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:null,purchase_state:'NOT_APPLICABLE',retail:120,retail_state:'VALID',weight:1}],coverage_rule:{allow_partial:false}});assert_(r.status==='BLOCKED_INVALID_MEMBER');return r;}));
    tests.push(test_('T72-022','Missing aggregate markup base is explicit',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:100,retail:120,weight:1}],coverage_rule:{allow_partial:false},base_markup:null,base_state:'MISSING'});approx_(r.aggregate_value,20);assert_(r.aggregate_base_value===null&&r.aggregate_change_pp===null&&r.base_status==='MISSING_BASE');return r;}));
    tests.push(test_('T72-023','Markup change is percentage-point difference',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:100,retail:120,weight:1}],coverage_rule:{allow_partial:false},base_markup:18.5,base_state:'VALID'});approx_(r.aggregate_change_pp,1.5);return r;}));
    tests.push(test_('T72-024','Markup rounds weighted levels before division',function(){var r=A.calculateAggregateMarkup({members:[{category_id:'A',purchase:1.0000004,retail:1.1000004,weight:1}],coverage_rule:{allow_partial:false}});approx_(r.weighted_purchase,1);approx_(r.weighted_retail,1.1);approx_(r.aggregate_value,10);return r;}));

    tests.push(test_('T72-025','Empty is missing and zero is zero',function(){assert_(A.Test.stateValue('', '', {}).state==='MISSING');assert_(A.Test.stateValue(null,'',{}).state==='MISSING');assert_(A.Test.stateValue('0','',{}).state==='ZERO');assert_(A.Test.stateValue(0,'',{}).state==='ZERO');return true;}));
    tests.push(test_('T72-026','Non-finite and unparsable values are invalid',function(){assert_(A.Test.stateValue(NaN,'',{}).state==='INVALID');assert_(A.Test.stateValue(Infinity,'',{}).state==='INVALID');assert_(A.Test.stateValue('abc','',{}).state==='INVALID');return true;}));
    tests.push(test_('T72-027','Invalid active weight blocks member',function(){[-1,0,null].forEach(function(weightValue){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:1,weight:weightValue}],coverage_rule:{allow_partial:false}});assert_(r.coverage.coverage_status==='INVALID'||r.status==='BLOCKED_INVALID_MEMBER');});return true;}));
    tests.push(test_('T72-028','Complete coverage ratio is one',function(){var c=A.Test.coverageResult(2,2,4,4,0,0,false);assert_(c.coverage_status==='COMPLETE'&&c.coverage_ratio===1);return c;}));
    tests.push(test_('T72-029','Partial coverage ratio uses applied over expected weight',function(){var c=A.Test.coverageResult(2,1,3,1,0,0,false);approx_(c.coverage_ratio,1/3,1e-10);return c;}));
    tests.push(test_('T72-030','All members not applicable',function(){var r=A.calculateNormalizedWeightedAverage({members:[{category_id:'A',value:null,value_state:'NOT_APPLICABLE',weight:1}],coverage_rule:{allow_partial:false}});assert_(r.status==='NOT_APPLICABLE'&&r.value===null);return r;}));
    tests.push(test_('T72-031','Invalid coverage takes precedence',function(){var c=A.Test.coverageResult(2,1,2,1,1,0,true);assert_(c.coverage_status==='INVALID'&&!c.publication_allowed);return c;}));
    tests.push(test_('T72-032','Partial result requires explicit policy',function(){var a=A.Test.coverageResult(2,1,2,1,0,0,false),b=A.Test.coverageResult(2,1,2,1,0,0,true);assert_(!a.publication_allowed&&b.publication_allowed);return{default:a,explicit:b};}));

    tests.push(test_('T72-033','Historical weight version is selected by period',function(){var weights=[weight_('G1','C1',0.2,{weight_version:'1',effective_to:'2025-12-31'}),weight_('G1','C1',0.8,{weight_version:'2',effective_from:'2026-01-01'})],members=[member_('G1','C1')],early=runBatch_({impact_items:[impact_({source_period:'2025-12-28',target_period:'2025-12-28'})],price_inputs:[price_('C1',10,{period_start:'2025-12-28'})],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}}),late=runBatch_({price_inputs:[price_('C1',10)],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}});approx_(categoryRow_(early,'C1').category_weight,0.2);approx_(categoryRow_(late,'C1').category_weight,0.8);return{early:categoryRow_(early,'C1').category_weight,late:categoryRow_(late,'C1').category_weight};}));
    tests.push(test_('T72-034','Conflicting effective weights are blocked',function(){var r=runBatch_({price_inputs:[price_('C1',4)],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',0.2,{weight_version:'1'}),weight_('G1','C1',0.3,{weight_version:'2'})]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1')]}});assert_(r.status==='SUCCESS_WITH_BLOCKED');assert_(r.diagnostics.some(function(d){return d.code==='CONTRACT_CONFLICT';}));return r.diagnostics;}));
    tests.push(test_('T72-035','Historical membership uses target period',function(){var rows=[member_('G1','C1',{membership_version:'1',effective_to:'2025-12-31'}),member_('G1','C2',{membership_version:'2',effective_from:'2026-01-01'})],weights=[weight_('G1','C1',1),weight_('G1','C2',1)],early=runBatch_({impact_items:[impact_({source_period:'2025-12-28',target_period:'2025-12-28'})],price_inputs:[price_('C1',4,{period_start:'2025-12-28'}),price_('C2',8,{period_start:'2025-12-28'})],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:rows}}),late=runBatch_({weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:rows}});assert_(categoryRow_(early,'C1')&&!categoryRow_(early,'C2'));assert_(categoryRow_(late,'C2')&&!categoryRow_(late,'C1'));return true;}));
    tests.push(test_('T72-036','Duplicate membership in one version is blocked',function(){var duplicate=member_('G1','C1'),r=runBatch_({price_inputs:[price_('C1',4)],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[duplicate,clone_(duplicate)]}});assert_(r.diagnostics.some(function(d){return d.code==='AGG_MEMBERSHIP_DUPLICATE';}));return r.diagnostics;}));
    tests.push(test_('T72-037','One category may belong to two aggregate subjects',function(){var defs=[definition_({aggregate_subject_id:'G1',aggregate_name:'G1'}),definition_({aggregate_subject_id:'G2',aggregate_name:'G2'})],members=[member_('G1','C1'),member_('G2','C1')],weights=[weight_('G1','C1',1),weight_('G2','C1',1)],r=runBatch_({price_inputs:[price_('C1',4)],aggregate_definitions:defs,weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}});assert_(r.rows.filter(function(row){return row.row_type==='AGGREGATE_RESULT';}).length===2);return r.rows;}));
    tests.push(test_('T72-038','Display-name change does not alter series key',function(){var a=A.Test.normalizeDefinition(definition_({aggregate_name:'Old'})),b=A.Test.normalizeDefinition(definition_({aggregate_name:'New'}));assert_(a.series_key===b.series_key);return a.series_key;}));
    tests.push(test_('T72-039','Rule identity or method change alters series key',function(){var a=A.Test.normalizeDefinition(definition_()),b=A.Test.normalizeDefinition(definition_({weight_rule_id:'WR2'})),c=A.Test.normalizeDefinition(definition_({membership_rule_id:'MR2'})),d=A.Test.normalizeDefinition(definition_({calculation_method:'NORMALIZED_WEIGHTED_AVERAGE'}));assert_(a.series_key!==b.series_key&&a.series_key!==c.series_key&&a.series_key!==d.series_key);return[a.series_key,b.series_key,c.series_key,d.series_key];}));
    tests.push(test_('T72-040','Unmergeable duplicate category row key is blocked',function(){var defs=[definition_({aggregate_subject_id:'G1'}),definition_({aggregate_subject_id:'G2'})],members=[member_('G1','C1',{allocation_factor:1}),member_('G2','C1',{allocation_factor:0.5})],weights=[weight_('G1','C1',1),weight_('G2','C1',1,{weight_scope:'G2'})],r=runBatch_({price_inputs:[price_('C1',4)],aggregate_definitions:defs,weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}});assert_(r.diagnostics.some(function(d){return d.code==='AGG_CALC_DUPLICATE_ROW_KEY';})||r.status==='SUCCESS_WITH_BLOCKED');return r.diagnostics;}));

    tests.push(test_('T72-041','Price-input order does not change result',function(){var a=runBatch_(),b=runBatch_({price_inputs:reverse_(request_().price_inputs)});equal_(a.rows,b.rows);assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));
    tests.push(test_('T72-042','Membership order does not change result',function(){var base=request_(),a=runBatch_(),b=runBatch_({membership_snapshot:{snapshot_id:'M1',hash:'MEMBERSHIP_HASH',rule_rows:reverse_(base.membership_snapshot.rule_rows)}});equal_(a.rows,b.rows);assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));
    tests.push(test_('T72-043','Impact order does not change result',function(){var impacts=[impact_({load_id:'L2',source_series_id:'S_C2',source_category_id:'C2'}),impact_()],a=runBatch_({impact_items:impacts}),b=runBatch_({impact_items:reverse_(impacts)});equal_(a.rows,b.rows);assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));
    tests.push(test_('T72-044','Calculator does not mutate request',function(){var req=request_(),before=JSON.stringify(req);A.calculateBatch(req);assert_(JSON.stringify(req)===before);return true;}));
    tests.push(test_('T72-045','Fingerprint ignores runtime metadata',function(){var base={rows:[{aggregate_row_key:'K',dataset_code:'D',created_at:'A',elapsed_ms:1}],diagnostics:[{code:'X',created_at:'A',elapsed_ms:1}]},other={rows:[{aggregate_row_key:'K',dataset_code:'D',created_at:'B',elapsed_ms:999}],diagnostics:[{code:'X',created_at:'B',elapsed_ms:999}]};assert_(A.buildCalculationFingerprint(base)===A.buildCalculationFingerprint(other));return A.buildCalculationFingerprint(base);}));
    tests.push(test_('T72-046','Calculator source contains no forbidden service APIs',function(){if(!opts.calculator_source)return skip_({reason:'calculator_source not supplied in this runtime'});['SpreadsheetApp','DriveApp','UrlFetchApp','LockService','PropertiesService','ScriptApp'].forEach(function(token){assert_(opts.calculator_source.indexOf(token)<0,'Forbidden API token found: '+token);});return true;}));

    tests.push(test_('T72-047','Each batch index is built once',function(){var r=runBatch_(),m=r.summary.metrics;assert_(m.price_index_builds===1&&m.definition_index_builds===1&&m.membership_index_builds===1&&m.weight_index_builds===1&&m.base_index_builds===1);return m;}));
    tests.push(test_('T72-048','No per-combination full price scan',function(){var categories=[],prices=[],weights=[],members=[],i;for(i=0;i<100;i+=1){categories.push('C'+i);prices.push(price_('C'+i,1));weights.push(weight_('G1','C'+i,0.01));members.push(member_('G1','C'+i));}var r=runBatch_({price_inputs:prices,weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}}),m=r.summary.metrics;assert_(m.price_inputs_inspected===100&&m.price_lookups===100&&m.price_inputs_inspected+m.price_lookups<100*100);return m;}));
    tests.push(test_('T72-049','Large in-memory fixture remains linear',function(){var n=1500,prices=[],weights=[],members=[],i;for(i=0;i<n;i+=1){prices.push(price_('C'+i,1));weights.push(weight_('G1','C'+i,1/n));members.push(member_('G1','C'+i));}var r=runBatch_({price_inputs:prices,weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}});assert_(r.summary.rows_total===n+1&&r.summary.metrics.price_inputs_inspected===n&&r.summary.metrics.price_lookups===n);return{rows:r.summary.rows_total,metrics:r.summary.metrics};}));
    tests.push(test_('T72-050','Empty impact returns no applicable items',function(){var r=runBatch_({impact_items:[]});assert_(r.ok&&r.status==='NO_APPLICABLE_ITEMS'&&r.rows.length===0);return r;}));
    tests.push(test_('T72-051','Mixed impact statuses calculate only eligible items',function(){var items=[impact_(),impact_({load_id:'L2',source_series_id:'S2',status:'BLOCKED_CONTRACT',contract_code:'AGG_FRONTIER_PERIOD_NOT_ALLOWED'}),impact_({load_id:'L3',source_series_id:'S3',status:'SKIPPED_NOT_APPLICABLE'})],r=runBatch_({impact_items:items});assert_(r.summary.impact_items_calculable===1&&r.summary.impact_items_non_calculable===2&&r.diagnostics.length===2);return r.summary;}));

    tests.push(test_('R72-001','Contribution unit mismatch blocks numeric result',function(){var r=runBatch_({price_inputs:[price_('C1',4,{unit:'rub'})],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1')]}}),row=aggregateRow_(r);assert_(r.status==='SUCCESS_WITH_BLOCKED'&&row&&row.calculation_status==='BLOCKED_INVALID_MEMBER'&&!row.publication_allowed);assert_(r.diagnostics.some(function(d){return d.code==='AGG_CALC_UNIT_MISMATCH';}));return{row:row,diagnostics:r.diagnostics};}));
    tests.push(test_('R72-002','Invalid current blocks even when partial coverage is allowed',function(){var r=runBatch_({price_inputs:[price_('C1',null,{change_pp:'',current_value:'bad',current_state:'INVALID'}),price_('C2',8)],aggregate_definitions:[definition_({coverage_rule_id:'ALLOW_PARTIAL'})],coverage_rules:[{coverage_rule_id:'ALLOW_PARTIAL',allow_partial:true}],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',0.5),weight_('G1','C2',0.5)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1'),member_('G1','C2')]}}),row=aggregateRow_(r);assert_(row.calculation_status==='BLOCKED_INVALID_MEMBER'&&!row.publication_allowed&&row.coverage_status==='INVALID');return row;}));
    tests.push(test_('R72-003','Invalid base blocks even when partial coverage is allowed',function(){var r=runBatch_({price_inputs:[price_('C1',null,{change_pp:'',base_value:'bad',base_state:'INVALID'}),price_('C2',8)],aggregate_definitions:[definition_({coverage_rule_id:'ALLOW_PARTIAL'})],coverage_rules:[{coverage_rule_id:'ALLOW_PARTIAL',allow_partial:true}],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',0.5),weight_('G1','C2',0.5)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1'),member_('G1','C2')]}}),row=aggregateRow_(r);assert_(row.calculation_status==='BLOCKED_INVALID_MEMBER'&&!row.publication_allowed&&row.coverage_status==='INVALID');return row;}));
    tests.push(test_('R72-004','Conflicting definitions are rejected independent of input order',function(){var a=definition_({aggregate_name:'A',coverage_rule_id:'DEFAULT_COMPLETE_ONLY'}),b=definition_({aggregate_name:'B',coverage_rule_id:'ALLOW_PARTIAL'}),coverage=[{coverage_rule_id:'ALLOW_PARTIAL',allow_partial:true}],x=runBatch_({aggregate_definitions:[a,b],coverage_rules:coverage}),y=runBatch_({aggregate_definitions:[b,a],coverage_rules:coverage});assert_(!x.ok&&!y.ok&&x.status==='FAILED_CONTRACT'&&y.status==='FAILED_CONTRACT');assert_(x.diagnostics[0].code==='AGG_CALC_DEFINITION_CONFLICT'&&y.diagnostics[0].code==='AGG_CALC_DEFINITION_CONFLICT');assert_(x.fingerprint===y.fingerprint);return{x:x.diagnostics[0],y:y.diagnostics[0],fingerprint:x.fingerprint};}));
    tests.push(test_('R72-005','Membership resolution inspects each rule row once',function(){var n=1200,prices=[],weights=[],members=[],i;for(i=0;i<n;i+=1){prices.push(price_('C'+i,1));weights.push(weight_('G1','C'+i,1/n));members.push(member_('G1','C'+i));}var r=runBatch_({price_inputs:prices,weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:weights},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:members}}),m=r.summary.metrics;assert_(m.membership_rows_inspected===n&&m.membership_candidates_inspected===n&&m.membership_duplicate_checks===n);return m;}));
    tests.push(test_('R72-006','Base input from a wrong period is never reused',function(){var def=definition_({value_type:'markup',calculation_method:'AGGREGATE_MARKUP',purchase_value_type:'purchase_price',retail_value_type:'retail_price'}),normalized=A.Test.normalizeDefinition(def),prices=[price_('C1',null,{series_id:'PURCHASE_C1',value_type:'purchase_price',current_value:100,base_value:null,change_pp:'',unit:'rub_per_kg'}),price_('C1',null,{series_id:'RETAIL_C1',value_type:'retail_price',current_value:120,base_value:null,change_pp:'',unit:'rub_per_kg'})],r=runBatch_({impact_items:[impact_({target_value_type:'markup'})],price_inputs:prices,aggregate_definitions:[def],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1')]},base_inputs:[{aggregate_series_key:normalized.series_key,base_period:'1999-01-01',base_value:10,value_state:'VALID'}]}),row=aggregateRow_(r);assert_(row.aggregate_value===20&&row.aggregate_base_value===null&&row.aggregate_change_pp===null&&row.base_status==='MISSING_BASE');return row;}));
    tests.push(test_('R72-007','All impacts are retained in output lineage',function(){var impacts=[impact_(),impact_({load_id:'L2',operation_id:'O2',source_series_id:'S_C2',source_category_id:'C2'})],r=runBatch_({impact_items:impacts}),ids=impacts.map(function(x){return C.normalizeImpactItem(x).impact_id;}).sort();assert_(r.rows.length>0);r.rows.forEach(function(row){equal_(row.source_impact_ids,ids);assert_(row.source_combo_keys&&row.source_combo_keys.length===2);});return{rows:r.rows.length,impact_ids:ids};}));
    tests.push(test_('R72-008','NOT_APPLICABLE contribution bypasses unit validation',function(){var r=runBatch_({price_inputs:[price_('C1',null,{current_value:null,base_value:null,change_pp:'',current_state:'NOT_APPLICABLE',value_state:'NOT_APPLICABLE',unit:'rub'})],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1')]}}),row=aggregateRow_(r);assert_(r.ok&&row.calculation_status==='NOT_APPLICABLE'&&row.coverage_status==='NOT_APPLICABLE'&&row.invalid_members_count===0);assert_(!r.diagnostics.some(function(d){return d.code==='AGG_CALC_UNIT_MISMATCH';}));return row;}));
    tests.push(test_('R72-009','NOT_APPLICABLE markup pair bypasses unit validation',function(){var def=definition_({value_type:'markup',calculation_method:'AGGREGATE_MARKUP',purchase_value_type:'purchase_price',retail_value_type:'retail_price'}),prices=[price_('C1',null,{series_id:'PURCHASE_C1',value_type:'purchase_price',current_value:null,base_value:null,change_pp:'',current_state:'NOT_APPLICABLE',value_state:'NOT_APPLICABLE',unit:''}),price_('C1',null,{series_id:'RETAIL_C1',value_type:'retail_price',current_value:null,base_value:null,change_pp:'',current_state:'NOT_APPLICABLE',value_state:'NOT_APPLICABLE',unit:'rub_per_kg'})],r=runBatch_({impact_items:[impact_({target_value_type:'markup'})],price_inputs:prices,aggregate_definitions:[def],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:[member_('G1','C1')]}}),row=aggregateRow_(r);assert_(r.ok&&row.calculation_status==='NOT_APPLICABLE'&&row.coverage_status==='NOT_APPLICABLE'&&row.invalid_members_count===0);assert_(!r.diagnostics.some(function(d){return d.code==='AGG_CALC_UNIT_MISMATCH';}));return row;}));
    tests.push(test_('R72-010','Lineage preserves valid impact and combo pairs',function(){var impacts=[impact_({load_id:'L_Z',operation_id:'O_Z',source_series_id:'S_Z'}),impact_({load_id:'L_A',operation_id:'O_A',source_series_id:'S_Q'}),impact_({load_id:'L_M',operation_id:'O_M',source_series_id:'S_A'})],normalized=impacts.map(function(x){return C.normalizeImpactItem(x);}),valid={};normalized.forEach(function(x){valid[x.impact_id+'|'+x.combo_key]=true;});var r=runBatch_({impact_items:impacts});r.rows.forEach(function(row){assert_(Array.isArray(row.source_impacts)&&row.source_impacts.length===3);assert_(row.source_impact_ids.length===row.source_combo_keys.length&&row.source_impacts.length===row.source_impact_ids.length);row.source_impacts.forEach(function(pair,index){assert_(valid[pair.impact_id+'|'+pair.combo_key]);assert_(row.source_impact_ids[index]===pair.impact_id&&row.source_combo_keys[index]===pair.combo_key);});assert_(valid[row.impact_id+'|'+row.combo_key]);});return{pairs:normalized.map(function(x){return{impact_id:x.impact_id,combo_key:x.combo_key};}),rows:r.rows.length};}));
    tests.push(test_('R72-011','Lineage aggregation is single-pass over output rows',function(){var n=400,impacts=[],i;for(i=0;i<n;i+=1)impacts.push(impact_({load_id:'L'+i,operation_id:'O'+i,source_series_id:'S'+i,source_category_id:'C1'}));var r=runBatch_({impact_items:impacts}),m=r.summary.metrics;assert_(m.lineage_pairs_collected===n);assert_(m.lineage_row_attachments===r.rows.length);r.rows.forEach(function(row){assert_(row.source_impacts.length===n);});return{impacts:n,rows:r.rows.length,metrics:m};}));
    tests.push(test_('R72-012','Duplicate category in one membership version is blocked across effective ranges',function(){var memberships=[member_('G1','C1',{effective_from:'2020-01-01',effective_to:'2026-06-30'}),member_('G1','C1',{effective_from:'2026-01-01',effective_to:''})],r=runBatch_({price_inputs:[price_('C1',4)],weight_snapshot:{snapshot_id:'W1',hash:'H',rule_rows:[weight_('G1','C1',1)]},membership_snapshot:{snapshot_id:'M1',hash:'H',rule_rows:memberships}});assert_(!r.ok&&r.status==='FAILED_CONTRACT');assert_(r.diagnostics.some(function(d){return d.code==='AGG_MEMBERSHIP_DUPLICATE';}));return r.diagnostics;}));

    var failed=tests.filter(function(t){return t.status==='FAIL';}),skipped=tests.filter(function(t){return t.status==='SKIP';});
    return {suite:'ALPHA72_PURE_CALCULATOR_TESTS',calculator_version:A.Version,total:tests.length,passed:tests.length-failed.length-skipped.length,failed:failed.length,skipped:skipped.length,status:failed.length?'FAILED':'SUCCESS',tests:tests};
  }

  function runLive(){
    return AKORT.Core.safeRun('ALPHA72_CALCULATOR_LIVE_SAFETY',function(){
      AKORT.EnvironmentGuard.assertDev();
      var before=AKORT.AggregateContract.inventory(),baseline=AKORT.AggregateContract.baselineInventory(),tests=[],pure=runPure();
      tests=tests.concat(pure.tests);
      tests.push(test_('T72-057','Pre-inventory equals accepted baseline',function(){var comparison=AKORT.AggregateContract.compareInventory(before,baseline);assert_(comparison.equal);assert_(before.rows===61636&&before.columns===29);assert_(before.data_hash==='1a6db3d0e56560cc908493fc3ced738d609cdb278bab5390764f090a52efd3f5');assert_(before.fingerprint==='459441b75a8020c361d8c2d5a16cb61293322b49e3c1483929cdf3ee3083624a');return comparison;}));
      var settings=AKORT.IncrementalPublish.runtimeSettings();
      tests.push(test_('T72-059','Physical aggregate execution remains disabled',function(){assert_(settings.aggregateExecutionEnabled===false&&settings.aggregateExecutionStatus==='DEFERRED_TO_ALPHA7');return settings;}));
      var after=AKORT.AggregateContract.inventory();
      tests.push(test_('T72-058','Post-inventory is unchanged',function(){assert_(before.rows===after.rows&&before.data_hash===after.data_hash&&before.fingerprint===after.fingerprint);return{before:before.data_hash,after:after.data_hash};}));
      tests.push(test_('T72-060','Calculator live suite performs no service write',function(){assert_(before.data_hash===after.data_hash);return{aggregate_writes:0,system_log_writes:0,lock_acquisitions:0};}));
      var failed=tests.filter(function(t){return t.status==='FAIL';}),skipped=tests.filter(function(t){return t.status==='SKIP';}),report={suite:'ALPHA72_CALCULATOR_LIVE_SAFETY',calculator_version:AKORT.AggregateCalculator.Version,total:tests.length,passed:tests.length-failed.length-skipped.length,failed:failed.length,skipped:skipped.length,status:failed.length?'FAILED':'SUCCESS',tests:tests,inventory:{before:before,after:after,baseline:baseline},compatibility_pending:['T72-052','T72-053','T72-054','T72-055','T72-056']};
      return failed.length?AKORT.Result.failure('ALPHA72_CALCULATOR_TESTS_FAILED','Alpha.7.2 calculator live safety suite failed.',report):AKORT.Result.success('Alpha.7.2 pure calculator and live safety gates passed; compatibility and golden parity gates remain required.',report);
    },{lock:false,persistLogs:false});
  }

  function status(){return{release_candidate:AKORT.AggregateCalculator.Release,calculator_version:AKORT.AggregateCalculator.Version,mode:'PURE_CALCULATION_WITH_READ_ONLY_LIVE_SAFETY',pure_test_ids:'T72-001..T72-051 + R72-001..R72-012',live_safety_test_ids:['T72-057','T72-058','T72-059','T72-060'],compatibility_pending:['T72-052','T72-053','T72-054','T72-055','T72-056'],acceptance_status:'PRE_ACCEPTANCE_NO_GO_UNTIL_GOLDEN_COMPATIBILITY_AND_LIVE_GATES_PASS'};}

  return Object.freeze({runPure:runPure,runLive:runLive,status:status});
})();

function AKORT_alpha72RunCalculatorTests(){var r=AKORT.Alpha72CalculatorTests.runLive(),d=r&&(r.data||r.details)||{},failed=(d.tests||[]).filter(function(x){return x.status==='FAIL';}).map(function(x){return{id:x.id,error:x.error};});console.log(JSON.stringify({ok:r.ok,status:r.status,code:r.code||'',message:r.message,total:d.total,passed:d.passed,failed:d.failed,skipped:d.skipped,failed_tests:failed,compatibility_pending:d.compatibility_pending||[]},null,2));return r;}
function AKORT_alpha72CalculatorStatus(){var data=AKORT.Alpha72CalculatorTests.status(),r=AKORT.Result.success('Alpha.7.2 calculator candidate status loaded.',data);console.log(JSON.stringify(r,null,2));return r;}
function AKORT_alpha72PureCalculatorProbe(){var report=AKORT.Alpha72CalculatorTests.runPure(),r=report.failed?AKORT.Result.failure('ALPHA72_PURE_TESTS_FAILED','Alpha.7.2 pure calculator probe failed.',report):AKORT.Result.success('Alpha.7.2 pure calculator probe passed.',report);console.log(JSON.stringify({ok:r.ok,status:r.status,total:report.total,passed:report.passed,failed:report.failed,skipped:report.skipped},null,2));return r;}
