var AKORT = typeof AKORT !== 'undefined' ? AKORT : {};

/**
 * Alpha.7.3 accepted indexed revision, reversal and latest-intent planner.
 * Pure planning only. Physical aggregate writes remain disabled.
 */
AKORT.AggregateRevisionPlanner = (function () {
  var VERSION='4.0-aggregate-revision-planner-2',RELEASE='4.0.0-alpha.7.3',MODE='PURE_READ_ONLY_PLANNING';
  var SORT_PLAN_FIELDS=Object.freeze(['dataset_code','frequency','aggregate_subject_id','value_type','index_type','target_period','definition_id','combo_key']);
  function contract_(){if(!AKORT.AggregateContract)throw plannerError_('ALPHA73_CONTRACT_UNAVAILABLE','Frozen Alpha.7.1 aggregate contract is unavailable.');return AKORT.AggregateContract;}
  function calculator_(){if(!AKORT.AggregateCalculator)throw plannerError_('ALPHA73_CALCULATOR_UNAVAILABLE','Frozen Alpha.7.2 aggregate calculator is unavailable.');return AKORT.AggregateCalculator;}
  function definitions_(){if(!AKORT.SpecialAggregateDefinitions)throw plannerError_('ALPHA73_DEFINITION_LAYER_UNAVAILABLE','Alpha.7.3 definition layer is unavailable.');return AKORT.SpecialAggregateDefinitions;}
  function plannerError_(code,message,details){var e=new Error(message);e.name='Alpha73RevisionPlannerError';e.code=code;e.details=details||{};return e;}
  function text_(v){return v===null||v===undefined?'':String(v).trim();}function norm_(v){return text_(v).toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ');}
  function clone_(v){if(Array.isArray(v))return v.map(clone_);if(v&&typeof v==='object'){if(v instanceof Date)return new Date(v.getTime());var o={};Object.keys(v).forEach(function(k){o[k]=clone_(v[k]);});return o;}return v;}
  function stable_(v){if(Array.isArray(v))return v.map(stable_);if(v&&typeof v==='object'){if(v instanceof Date)return v.toISOString();var o={};Object.keys(v).sort().forEach(function(k){if(['created_at','elapsed_ms','started_at','finished_at','logging_metadata','executed_at','updated_at'].indexOf(k)<0)o[k]=stable_(v[k]);});return o;}if(typeof v==='number'&&!isFinite(v))return null;return v;}
  function stableStringify_(v){return JSON.stringify(stable_(v));}function hash_(v){return calculator_().Test.sha256(stableStringify_(v));}
  function requireText_(o,f,c){var v=text_(o&&o[f]);if(!v)throw plannerError_(c||'ALPHA73_DEPENDENCY_INVALID','Required planner field is missing: '+f+'.',{field:f});return v;}
  function compareByFields_(fields){return function(a,b){var l=fields.map(function(f){return text_(a[f]);}).join('|'),r=fields.map(function(f){return text_(b[f]);}).join('|');return l<r?-1:l>r?1:0;};}
  function uniqueSorted_(values){var m={};(values||[]).forEach(function(v){var k=text_(v);if(k)m[k]=true;});return Object.keys(m).sort();}function canonicalArray_(values){return clone_(values||[]).sort(function(a,b){var l=stableStringify_(a),r=stableStringify_(b);return l<r?-1:l>r?1:0;});}
  function diagnostic_(ctx,severity,code,message,details){var s=ctx||{};return{impact_id:text_(s.impact_id),combo_key:text_(s.combo_key),aggregate_subject_id:text_(s.aggregate_subject_id),period_start:text_(s.target_period||s.period_start),severity:severity,code:code,message:message,details:clone_(details||{})};}
  function validateFrontier_(request){var f=request&&request.frontier;return contract_().validateFrontier(f,text_(request.frontier_snapshot_id||f&&f.snapshot_id),text_(request.frontier_hash||f&&f.hash));}
  function frontierParts_(key){var p=String(key||'').split('|');return{frequency:p[0]||'',dataset_code:p[1]||'',series_scope:p[2]||'',period:p.slice(3).join('|')};}
  function snapshotIdentity_(snapshot,label){if(!snapshot||typeof snapshot!=='object')throw plannerError_('ALPHA73_SNAPSHOT_REQUIRED',label+' snapshot is required.',{label:label});var id=requireText_(snapshot,'snapshot_id','ALPHA73_SNAPSHOT_REQUIRED'),rows=canonicalArray_(Array.isArray(snapshot.rule_rows)?snapshot.rule_rows:[]),computed=hash_(rows),declared=text_(snapshot.hash);return{snapshot_id:id,hash:declared||computed,computed_hash:computed,rows_count:rows.length};}
  function validateSnapshotReference_(impact,weightIdentity,membershipIdentity){if(text_(impact.weight_snapshot_id)!==weightIdentity.snapshot_id)throw plannerError_('ALPHA73_WEIGHT_SNAPSHOT_MISMATCH','Impact weight_snapshot_id does not match supplied snapshot.',{impact:impact.weight_snapshot_id,supplied:weightIdentity.snapshot_id});if(text_(impact.membership_snapshot_id)!==membershipIdentity.snapshot_id)throw plannerError_('ALPHA73_MEMBERSHIP_SNAPSHOT_MISMATCH','Impact membership_snapshot_id does not match supplied snapshot.',{impact:impact.membership_snapshot_id,supplied:membershipIdentity.snapshot_id});}
  function familyKey_(d){return definitions_().Test.definitionFamilyKey(d);}function datasetFrequencyKey_(dataset,frequency){return text_(dataset)+'|'+norm_(frequency);}function membershipKey_(rule,subject,category){return[text_(rule),text_(subject),text_(category)].join('|');}
  function buildIndexes_(definitions,membershipRows,frontier){var metrics={definition_index_builds:1,membership_index_builds:1,frontier_index_builds:1,definition_rows_indexed:0,definition_families_indexed:0,membership_rows_indexed:0,frontier_keys_indexed:0,source_impacts_inspected:0,family_candidates_inspected:0,dependency_candidates:0,membership_candidates_inspected:0,calculation_batches:0};var families={},byDatasetFrequency={},members={},periods={};
    (definitions||[]).forEach(function(d){metrics.definition_rows_indexed+=1;var fk=familyKey_(d);if(!families[fk]){families[fk]=[];metrics.definition_families_indexed+=1;var dk=datasetFrequencyKey_(d.dataset_code,d.frequency);byDatasetFrequency[dk]=byDatasetFrequency[dk]||[];byDatasetFrequency[dk].push(fk);}families[fk].push(d);});Object.keys(families).forEach(function(k){families[k].sort(compareByFields_(['effective_from','definition_version','definition_id']));});Object.keys(byDatasetFrequency).forEach(function(k){byDatasetFrequency[k]=uniqueSorted_(byDatasetFrequency[k]);});
    (membershipRows||[]).forEach(function(r){metrics.membership_rows_indexed+=1;var k=membershipKey_(r.membership_rule_id,r.aggregate_subject_id,r.category_id);members[k]=members[k]||[];members[k].push(r);});Object.keys(members).forEach(function(k){members[k].sort(compareByFields_(['effective_from','membership_version']));});
    Object.keys(frontier.keys||{}).sort().forEach(function(k){if(frontier.keys[k]!==true)return;metrics.frontier_keys_indexed+=1;var p=frontierParts_(k),pk=[p.frequency,p.dataset_code,p.series_scope].join('|');periods[pk]=periods[pk]||[];periods[pk].push(p.period);});Object.keys(periods).forEach(function(k){periods[k]=uniqueSorted_(periods[k]);});return{families:families,by_dataset_frequency:byDatasetFrequency,members:members,periods:periods,metrics:metrics};}
  function periodsFor_(indexes,frequency,dataset,scope){var exact=indexes.periods[[norm_(frequency),text_(dataset),text_(scope||'ALL')].join('|')]||[],all=indexes.periods[[norm_(frequency),text_(dataset),'ALL'].join('|')]||[];return uniqueSorted_(exact.concat(all));}
  function activeDefinition_(family,period){var active=(family||[]).filter(function(d){return definitions_().Test.activeAt(d,period);});if(active.length>1)throw plannerError_('ALPHA73_DEFINITION_CONFLICT','More than one effective definition resolves for target period.',{period:period,definition_ids:active.map(function(d){return d.definition_id;})});return active.length?active[0]:null;}
  function sourceValueMatches_(definition,impact){var t=text_(impact.source_value_type);if(!t)return true;if(definition.calculation_method==='AGGREGATE_MARKUP')return[definition.purchase_value_type,definition.retail_value_type,'markup'].indexOf(t)>=0;return text_(definition.value_type)===t;}
  function membershipActive_(definition,impact,period,indexes){var category=text_(impact.source_category_id);if(!category)return true;var rows=indexes.members[membershipKey_(definition.membership_rule_id,definition.aggregate_subject_id,category)]||[];indexes.metrics.membership_candidates_inspected+=rows.length;var active=rows.filter(function(r){return definitions_().Test.activeAt(r,period);});if(active.length>1)throw plannerError_('ALPHA73_RULE_VERSION_CONFLICT','More than one membership row is active for category and target period.',{category_id:category,period:period,rows:active});return active.length===1;}
  function normalizedSourceImpact_(impact){var s=impact||{};return{impact_id:text_(s.impact_id),load_id:requireText_(s,'load_id'),operation_id:text_(s.operation_id||'ALPHA73_PLAN'),reason_code:text_(s.reason_code||'REVISION'),source_dataset_code:requireText_({v:s.source_dataset_code||s.dataset_code},'v'),source_series_id:requireText_({v:s.source_series_id||s.series_id},'v'),source_category_id:text_(s.source_category_id||s.category_id),source_period:requireText_({v:s.source_period||s.period_start||s.period},'v'),frequency:norm_(requireText_(s,'frequency')),source_value_type:text_(s.source_value_type||s.value_type||s.target_value_type),source_series_scope:text_(s.source_series_scope||'ALL'),weight_snapshot_id:requireText_(s,'weight_snapshot_id'),membership_snapshot_id:requireText_(s,'membership_snapshot_id'),created_at:text_(s.created_at||'1970-01-01T00:00:00.000Z')};}
  function impactForDefinition_(source,definition,targetPeriod,frontier,status,code,reason){return contract_().normalizeImpactItem({load_id:source.load_id,operation_id:source.operation_id,reason_code:source.reason_code,source_dataset_code:source.source_dataset_code,source_series_id:source.source_series_id,source_category_id:source.source_category_id,source_period:source.source_period,frequency:source.frequency,target_aggregate_scope:definition.aggregate_subject_id,target_value_type:definition.value_type,target_index_type:definition.index_type,target_period:targetPeriod,weight_snapshot_id:source.weight_snapshot_id,membership_snapshot_id:source.membership_snapshot_id,frontier_snapshot_id:frontier.snapshot_id,status:status,contract_code:code||'',blocked_reason:reason||'',created_at:source.created_at});}
  function calculationKey_(definition,targetPeriod){return[definition.aggregate_series_key||definition.series_key,contract_().Test.periodKey(definition.frequency,targetPeriod)].join('|');}
  function sharedInputs_(source,weightIdentity,membershipIdentity){var weightSnapshot=clone_(source.weight_snapshot),membershipSnapshot=clone_(source.membership_snapshot);weightSnapshot.rule_rows=canonicalArray_(weightSnapshot.rule_rows||[]);membershipSnapshot.rule_rows=canonicalArray_(membershipSnapshot.rule_rows||[]);var shared={price_inputs:canonicalArray_(source.price_inputs||[]),weight_snapshot:weightSnapshot,membership_snapshot:membershipSnapshot,coverage_rules:canonicalArray_(source.coverage_rules||[]),base_inputs:canonicalArray_(source.base_inputs||[]),options:clone_(source.calculator_options||{}),identities:{weight:weightIdentity,membership:membershipIdentity}};shared.fingerprint=hash_({price_inputs:shared.price_inputs,weight_snapshot:weightIdentity,membership_snapshot:membershipIdentity,coverage_rules:shared.coverage_rules,base_inputs:shared.base_inputs,options:shared.options});return shared;}
  function compactBatch_(request,item,index,shared){var impacts=item.impacts.slice().sort(compareByFields_(['combo_key','impact_id']));return{contract_version:contract_().Version,calculation_id:'ALPHA73_CALC_'+hash_([request.plan_id,index,item.calculation_key,impacts.map(function(i){return i.combo_key;})]).slice(0,20).toUpperCase(),impact_items:impacts,aggregate_definitions:[clone_(item.definition)],shared_input_fingerprint:shared.fingerprint};}
  function hydrateBatch_(batch,shared){return{contract_version:batch.contract_version,calculation_id:batch.calculation_id,impact_items:batch.impact_items,aggregate_definitions:batch.aggregate_definitions,price_inputs:shared.price_inputs,weight_snapshot:shared.weight_snapshot,membership_snapshot:shared.membership_snapshot,coverage_rules:shared.coverage_rules,base_inputs:shared.base_inputs,options:shared.options};}
  function plannedAggregateIdentity_(definition,targetPeriod){var row=clone_(definition);row.period_start=targetPeriod;if(row.aggregate_level==='group')row.group_id=row.aggregate_subject_id;return{aggregate_series_key:definition.aggregate_series_key||contract_().aggregateSeriesKey(row),aggregate_row_key:contract_().aggregateRowKey(row),frequency:definition.frequency,period_start:contract_().Test.periodKey(definition.frequency,targetPeriod),row_type:'AGGREGATE_RESULT'};}
  function buildLatestIntents(rows,frontier){var source=frontier||{},existing=clone_(source.rows||[]),planned=clone_(rows||[]),excluded={},existingByKey={},plannedByKey={},affected={},preBySeries={};(source.excluded_row_keys||[]).forEach(function(k){excluded[text_(k)]=true;});
    existing.forEach(function(r){var series=text_(r.aggregate_series_key||r.series_key),key=text_(r.aggregate_row_key||r.row_key);if(!series||!key)return;existingByKey[key]=r;preBySeries[series]=preBySeries[series]||[];preBySeries[series].push(r);});
    planned.forEach(function(r){var series=text_(r.aggregate_series_key||r.series_key),key=text_(r.aggregate_row_key||r.row_key);if(!series||!key)return;plannedByKey[key]=r;affected[series]=true;});Object.keys(excluded).forEach(function(k){if(existingByKey[k])affected[text_(existingByKey[k].aggregate_series_key||existingByKey[k].series_key)]=true;});
    var intents=[],conflicts=[];Object.keys(affected).sort().forEach(function(series){var pre=(preBySeries[series]||[]),current=pre.filter(function(r){return Number(r.is_latest_period||0)===1;});if(current.length>1){conflicts.push({series_key:series,code:'ALPHA73_LATEST_CONFLICT',phase:'PRE_CHANGE',rows:current.map(function(r){return text_(r.aggregate_row_key||r.row_key);}).sort()});return;}var previous=current.length?text_(current[0].aggregate_row_key||current[0].row_key):'';var map={};pre.forEach(function(r){map[text_(r.aggregate_row_key||r.row_key)]=r;});Object.keys(plannedByKey).forEach(function(k){var r=plannedByKey[k],s=text_(r.aggregate_series_key||r.series_key);if(s===series)map[k]=r;});Object.keys(excluded).forEach(function(k){delete map[k];});var values=Object.keys(map).map(function(k){var r=map[k];return{row_key:k,period:contract_().Test.periodKey(r.frequency,r.period_start||r.target_period)};}).sort(function(a,b){return a.period<b.period?-1:a.period>b.period?1:a.row_key<b.row_key?-1:1;});var max=values.length?values[values.length-1].period:'',maxima=values.filter(function(v){return v.period===max;});if(maxima.length>1){conflicts.push({series_key:series,code:'ALPHA73_LATEST_CONFLICT',phase:'POST_CHANGE',rows:maxima.map(function(v){return v.row_key;}).sort(),period:max});return;}var next=maxima.length?maxima[0].row_key:'';if(previous!==next)intents.push({aggregate_series_key:series,previous_latest_row_key:previous,next_latest_row_key:next,reason:previous?(next?'LATEST_CHANGED':'LATEST_CLEARED'):'LATEST_INITIALIZED',evidence:{max_period:max,affected_series:true}});});intents.sort(compareByFields_(['aggregate_series_key','previous_latest_row_key','next_latest_row_key']));conflicts.sort(compareByFields_(['series_key','phase','code']));return{intents:intents,conflicts:conflicts,fingerprint:hash_({intents:intents,conflicts:conflicts})};}
  function buildInputFingerprint_(source,weightIdentity,membershipIdentity,frontier){return hash_({source_impacts:canonicalArray_(source.source_impacts||[]),definitions:definitions_().buildDefinitionFingerprint({definitions:source.definitions||[],membership_rows:source.membership_snapshot&&source.membership_snapshot.rule_rows||source.membership_rows||[]}),frontier:{snapshot_id:frontier.snapshot_id,hash:frontier.hash,count:frontier.count},weight_snapshot:weightIdentity,membership_snapshot:membershipIdentity,price_inputs:canonicalArray_(source.price_inputs||[]),coverage_rules:canonicalArray_(source.coverage_rules||[]),base_inputs:canonicalArray_(source.base_inputs||[]),calculator_options:source.calculator_options||{},execute_calculator:source.execute_calculator===true});}
  function planRevision(request){var source=clone_(request||{}),diagnostics=[],revisionItems=[],batches=[],rows=[],calculations=[],metrics={};try{if(!Array.isArray(source.source_impacts))throw plannerError_('ALPHA73_DEPENDENCY_INVALID','source_impacts must be an array.');var definitions=clone_(source.definitions||[]);if(!definitions.length)throw plannerError_('ALPHA73_DEFINITION_MISSING','No Alpha.7.3 definitions were supplied.');definitions_().Test.validateDefinitions(definitions);var membershipRows=clone_(source.membership_snapshot&&source.membership_snapshot.rule_rows||source.membership_rows||[]);definitions_().Test.validateMembershipRows(membershipRows);var frontier=validateFrontier_(source),weightIdentity=snapshotIdentity_(source.weight_snapshot,'weight'),membershipIdentity=snapshotIdentity_(source.membership_snapshot,'membership'),indexes=buildIndexes_(definitions,membershipRows,frontier);metrics=indexes.metrics;var inputFingerprint=buildInputFingerprint_(source,weightIdentity,membershipIdentity,frontier),planId=text_(source.plan_id||'ALPHA73_PLAN_'+inputFingerprint.slice(0,20).toUpperCase());source.plan_id=planId;var shared=sharedInputs_(source,weightIdentity,membershipIdentity),planMap={},matchedByImpact={};
    source.source_impacts.forEach(function(raw){metrics.source_impacts_inspected+=1;var impact=normalizedSourceImpact_(raw);validateSnapshotReference_(impact,weightIdentity,membershipIdentity);var familyKeys=indexes.by_dataset_frequency[datasetFrequencyKey_(impact.source_dataset_code,impact.frequency)]||[];matchedByImpact[impact.load_id+'|'+impact.source_series_id]=0;familyKeys.forEach(function(fk){metrics.family_candidates_inspected+=1;var family=indexes.families[fk],representative=family[0],periods=periodsFor_(indexes,representative.frequency,representative.dataset_code,impact.source_series_scope),candidates=contract_().dependencyCandidates(representative.frequency,impact.source_period,representative.index_type,periods);metrics.dependency_candidates+=candidates.length;candidates.forEach(function(candidate){var definition=activeDefinition_(family,candidate);if(!definition||!sourceValueMatches_(definition,impact)||!membershipActive_(definition,impact,candidate,indexes))return;var allowed=contract_().frontierAllows(frontier,definition.frequency,definition.dataset_code,impact.source_series_scope||'ALL',candidate),normalized=impactForDefinition_(impact,definition,candidate,frontier,allowed?'PLANNED':'BLOCKED_CONTRACT',allowed?'':'ALPHA73_PERIOD_OUTSIDE_FRONTIER',allowed?'':'Dependent period is outside immutable existing-period frontier.'),key=calculationKey_(definition,candidate);if(!planMap[key])planMap[key]={dataset_code:definition.dataset_code,frequency:definition.frequency,aggregate_subject_id:definition.aggregate_subject_id,value_type:definition.value_type,index_type:definition.index_type,target_period:candidate,definition_id:definition.definition_id,definition:definition,status:normalized.status,contract_code:normalized.contract_code,combo_key:normalized.combo_key,calculation_key:key,impacts:[],lineage:{}};if(planMap[key].status!==normalized.status)throw plannerError_('ALPHA73_DUPLICATE_COMBO','One calculation key has conflicting statuses.',{key:key});var pairKey=normalized.impact_id+'|'+normalized.combo_key;if(!planMap[key].lineage[pairKey]){planMap[key].lineage[pairKey]={impact_id:normalized.impact_id,combo_key:normalized.combo_key};planMap[key].impacts.push(normalized);}matchedByImpact[impact.load_id+'|'+impact.source_series_id]+=1;});});if(!matchedByImpact[impact.load_id+'|'+impact.source_series_id])diagnostics.push(diagnostic_(impact,'WARNING','ALPHA73_DEFINITION_MISSING','No effective special aggregate definition and membership are affected at any existing target period.',{source_category_id:impact.source_category_id}));});
    Object.keys(planMap).sort().forEach(function(key,index){var item=planMap[key];item.impacts=canonicalArray_(item.impacts||[]);item.combo_key=item.impacts.length?item.impacts[0].combo_key:'';item.source_impacts=Object.keys(item.lineage).sort().map(function(k){return item.lineage[k];});delete item.lineage;revisionItems.push(clone_(item));if(item.status!=='PLANNED'){diagnostics.push(diagnostic_(item,'WARNING',item.contract_code||'ALPHA73_PERIOD_OUTSIDE_FRONTIER','Revision item is blocked by contract.',{calculation_key:key}));return;}var batch=compactBatch_(source,item,index,shared);batches.push(batch);if(source.execute_calculator===true){var calculated=calculator_().calculateBatch(hydrateBatch_(batch,shared));calculations.push(calculated);if(!calculated.ok)diagnostics.push(diagnostic_(item,'ERROR','ALPHA73_CALCULATOR_FAILED','Frozen calculator rejected Alpha.7.3 batch.',{status:calculated.status,diagnostics:calculated.diagnostics}));rows=rows.concat(calculated.rows||[]);}});metrics.calculation_batches=batches.length;revisionItems.sort(compareByFields_(SORT_PLAN_FIELDS));batches.sort(compareByFields_(['calculation_id']));rows.sort(compareByFields_(['aggregate_series_key','period_start','aggregate_row_key']));var latest={intents:[],conflicts:[],fingerprint:hash_({deferred:true})},latestStatus='DEFERRED_UNTIL_CALCULATED_ROWS';if(source.execute_calculator===true){latest=buildLatestIntents(rows,source.latest_frontier||{rows:source.existing_aggregate_rows||[],excluded_row_keys:source.excluded_row_keys||[]});latestStatus=latest.conflicts.length?'CONFLICT':'READY';latest.conflicts.forEach(function(c){diagnostics.push(diagnostic_({aggregate_subject_id:c.series_key},'ERROR',c.code,'Latest-period identity is ambiguous; no physical execution is permitted.',c));});}
    diagnostics.sort(compareByFields_(['severity','code','impact_id','combo_key','period_start']));var errors=diagnostics.filter(function(d){return d.severity==='ERROR';}).length,result={ok:errors===0,status:errors?'FAILED_CONTRACT':'SUCCESS',release:RELEASE,plan_id:planId,input_fingerprint:inputFingerprint,source_impacts:canonicalArray_(source.source_impacts),revision_items:revisionItems,calculator_shared_input:shared,calculator_batches:batches,calculations:calculations,planned_rows:rows,latest_intents:latest.intents,latest_conflicts:latest.conflicts,latest_status:latestStatus,diagnostics:diagnostics,summary:{revision_items_total:revisionItems.length,planned_items:revisionItems.filter(function(x){return x.status==='PLANNED';}).length,blocked_items:revisionItems.filter(function(x){return x.status!=='PLANNED';}).length,calculator_batches:batches.length,planned_rows:rows.length,metrics:metrics}};if(result.ok&&(result.summary.blocked_items||diagnostics.length))result.status='SUCCESS_WITH_BLOCKED';result.fingerprint=buildPlanFingerprint(result);return result;
  }catch(error){diagnostics.push(diagnostic_({},'ERROR',text_(error&&error.code||'ALPHA73_DEPENDENCY_INVALID'),text_(error&&error.message||error),error&&error.details||{}));var failed={ok:false,status:'FAILED_CONTRACT',release:RELEASE,plan_id:text_(source.plan_id),input_fingerprint:'',source_impacts:canonicalArray_(source.source_impacts||[]),revision_items:[],calculator_shared_input:null,calculator_batches:[],calculations:[],planned_rows:[],latest_intents:[],latest_conflicts:[],latest_status:'NOT_EVALUATED',diagnostics:diagnostics,summary:{revision_items_total:0,planned_items:0,blocked_items:0,calculator_batches:0,planned_rows:0,metrics:metrics}};failed.fingerprint=buildPlanFingerprint(failed);return failed;}}
  function planReversal(request){var source=clone_(request||{});try{if(source.has_current_effect===false){var noEffect={ok:true,status:'NO_CURRENT_EFFECT',release:RELEASE,plan_id:text_(source.plan_id||'ALPHA73_REVERSAL_NO_EFFECT'),source_impacts:clone_(source.source_impacts||[]),reversal_items:[],calculator_shared_input:null,calculator_batches:[],calculations:[],planned_rows:[],latest_intents:[],latest_conflicts:[],latest_status:'NOT_REQUIRED',diagnostics:[diagnostic_({},'INFO','ALPHA73_NO_CURRENT_EFFECT','The reversed load has no current accepted aggregate effect.',{})],summary:{reversal_items_total:0,calculator_batches:0,planned_rows:0}};noEffect.fingerprint=buildPlanFingerprint(noEffect);return noEffect;}if(source.has_current_effect!==true||!source.current_effect_evidence||typeof source.current_effect_evidence!=='object'||!Object.keys(source.current_effect_evidence).length)throw plannerError_('ALPHA73_CURRENT_EFFECT_EVIDENCE_REQUIRED','Reversal requires explicit positive evidence of the current accepted effect.');if(!Array.isArray(source.previous_price_inputs))throw plannerError_('ALPHA73_PREVIOUS_INPUTS_REQUIRED','previous_price_inputs are required for reversal.');source.price_inputs=clone_(source.previous_price_inputs);source.base_inputs=clone_(source.previous_base_inputs||[]);source.source_impacts=(source.source_impacts||[]).map(function(i){var r=clone_(i);r.reason_code='REVERSAL';return r;});source.excluded_row_keys=clone_(source.current_effect_row_keys||source.excluded_row_keys||[]);var result=planRevision(source);result.reversal_items=clone_(result.revision_items||[]);delete result.revision_items;result.summary.reversal_items_total=result.reversal_items.length;result.current_effect_evidence=clone_(source.current_effect_evidence);result.fingerprint=buildPlanFingerprint(result);return result;}catch(error){var failed={ok:false,status:'FAILED_CONTRACT',release:RELEASE,plan_id:text_(source.plan_id),source_impacts:clone_(source.source_impacts||[]),reversal_items:[],calculator_shared_input:null,calculator_batches:[],calculations:[],planned_rows:[],latest_intents:[],latest_conflicts:[],latest_status:'NOT_EVALUATED',diagnostics:[diagnostic_({},'ERROR',text_(error&&error.code||'ALPHA73_REVERSAL_INVALID'),text_(error&&error.message||error),error&&error.details||{})],summary:{reversal_items_total:0,calculator_batches:0,planned_rows:0}};failed.fingerprint=buildPlanFingerprint(failed);return failed;}}
  function buildPlanFingerprint(plan){var s=clone_(plan||{}),canonical={status:s.status,plan_id:s.plan_id,input_fingerprint:s.input_fingerprint||'',source_impacts:s.source_impacts||[],definitions:s.definitions||[],frontier:s.frontier||null,weight_snapshot:s.weight_snapshot||null,membership_snapshot:s.membership_snapshot||null,price_inputs:s.price_inputs||[],coverage_rules:s.coverage_rules||[],base_inputs:s.base_inputs||[],calculator_options:s.calculator_options||{},revision_items:s.revision_items||[],reversal_items:s.reversal_items||[],calculator_shared_input:s.calculator_shared_input?{fingerprint:s.calculator_shared_input.fingerprint,identities:s.calculator_shared_input.identities}:null,calculator_batches:(s.calculator_batches||[]).map(function(b){return{calculation_id:b.calculation_id,impact_items:b.impact_items,aggregate_definitions:b.aggregate_definitions,shared_input_fingerprint:b.shared_input_fingerprint};}),planned_rows:s.planned_rows||[],latest_intents:s.latest_intents||[],latest_conflicts:s.latest_conflicts||[],latest_status:s.latest_status||'',diagnostics:s.diagnostics||[],current_effect_evidence:s.current_effect_evidence||null};return hash_(canonical);}
  function statusSummary(){return{release_candidate:RELEASE,planner_contract_version:VERSION,mode:MODE,physical_writes:false,frozen_calculator_version:calculator_().Version,frozen_definition_version:definitions_().Version,acceptance_status:'ACCEPTED_AND_CLOSED',execution_model:'INDEX_ONCE_GROUPED_BATCHES_SHARED_INPUTS'};}
  return Object.freeze({Version:VERSION,Release:RELEASE,Mode:MODE,planRevision:planRevision,planReversal:planReversal,buildLatestIntents:buildLatestIntents,buildPlanFingerprint:buildPlanFingerprint,statusSummary:statusSummary,Test:Object.freeze({clone:clone_,stableStringify:stableStringify_,hash:hash_,frontierParts:frontierParts_,snapshotIdentity:snapshotIdentity_,buildIndexes:buildIndexes_,activeDefinition:activeDefinition_,membershipActive:membershipActive_,normalizedSourceImpact:normalizedSourceImpact_,plannedAggregateIdentity:plannedAggregateIdentity_,plannerError:plannerError_})});
})();
