var AKORT = typeof AKORT !== 'undefined' ? AKORT : {};

/** Alpha.7.3 pure and read-only acceptance probes. */
AKORT.Alpha73Tests = (function () {
  function C_(){return AKORT.AggregateContract;}
  function A_(){return AKORT.AggregateCalculator;}
  function D_(){return AKORT.SpecialAggregateDefinitions;}
  function P_(){return AKORT.AggregateRevisionPlanner;}
  function text_(value){return value===null||value===undefined?'':String(value).trim();}
  function clone_(value){if(Array.isArray(value))return value.map(clone_);if(value&&typeof value==='object'){if(value instanceof Date)return new Date(value.getTime());var out={};Object.keys(value).forEach(function(k){out[k]=clone_(value[k]);});return out;}return value;}
  function assert_(condition,message){if(!condition)throw new Error(message||'Assertion failed.');}
  function equal_(actual,expected,message){if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error((message||'Values differ')+': expected '+JSON.stringify(expected)+', got '+JSON.stringify(actual));}
  function approx_(actual,expected,tolerance,message){var limit=tolerance===undefined?0.000001:Number(tolerance);if(Math.abs(Number(actual)-Number(expected))>limit)throw new Error((message||'Values differ')+': expected '+expected+', got '+actual);}
  function stored6Approx_(actual,expected,message){var actualMicros=Math.round(Number(actual)*1000000),expectedMicros=Math.round(Number(expected)*1000000);if(!isFinite(actualMicros)||!isFinite(expectedMicros)||Math.abs(actualMicros-expectedMicros)>1)throw new Error((message||'Stored six-decimal values differ')+': expected '+expected+', got '+actual);}
  function test_(id,name,fn){try{return{id:id,name:name,status:'PASS',data:fn(),error:null};}catch(error){return{id:id,name:name,status:'FAIL',data:null,error:{name:text_(error&&error.name),code:text_(error&&error.code),message:text_(error&&error.message||error),details:error&&error.details||null,stack:text_(error&&error.stack)}};}}
  function skip_(id,name,reason){return{id:id,name:name,status:'SKIP',data:{reason:reason},error:null};}

  function borshchMap_(){return[
    {category_id:'CABBAGE',category_name:'Капуста белокочанная',allocation_factor:1},
    {category_id:'POTATO',category_name:'Картофель',allocation_factor:1},
    {category_id:'ONION',category_name:'Лук репчатый',allocation_factor:1},
    {category_id:'CARROT',category_name:'Морковь',allocation_factor:1},
    {category_id:'BEET',category_name:'Свекла',allocation_factor:1}
  ];}
  function borshchScope_(overrides){var out={dataset_codes:['D'],frequencies:['weekly'],definition_version:'BORSHCH_DEF_V1',membership_rule_id:'BORSHCH_RULE',membership_version:'BORSHCH_MEMBERSHIP_V1',weight_rule_id:'W',weight_scope:'dashboard_basket',source_map:borshchMap_(),value_types:['retail_price'],index_types:['wow'],effective_from:'2020-01-01',provenance:'TEST_SOURCE_MAP',source_map_id:'TEST_BORSHCH_MAP_V1'};Object.keys(overrides||{}).forEach(function(k){out[k]=overrides[k];});return out;}
  function builtBorshch_(overrides){return D_().buildBorshchDefinitions(borshchScope_(overrides));}
  function weightRows_(categories,scope){return(categories||borshchMap_().map(function(x){return x.category_id;})).map(function(category,index){return{weight_rule_id:'W',weight_version:'WV1',weight_scope:scope||'dashboard_basket',category_id:category,weight_value:index+1,effective_from:'2020-01-01',effective_to:'',status:'ACTIVE'};});}
  function priceRows_(frequency,indexType,period,valueType,values){var categories=borshchMap_().map(function(x){return x.category_id;});return categories.map(function(category,index){var current=100+index*10,change=(values&&values[index]!==undefined)?values[index]:(index+1)*10;return{dataset_code:'D',frequency:frequency||'weekly',series_id:'S_'+category+'_'+(valueType||'retail_price'),category_id:category,value_type:valueType||'retail_price',index_type:indexType||'wow',period_start:period||'2026-01-04',current_value:current,base_value:100,change_pp:change,unit:valueType==='markup'?'percent':'percentage_point',value_state:'VALID',current_state:'VALID',base_state:'VALID',change_state:'VALID'};});}
  function impact_(overrides){var out={load_id:'L1',operation_id:'O1',reason_code:'REVISION',source_dataset_code:'D',source_series_id:'SRC',source_category_id:'CABBAGE',source_period:'2026-01-04',frequency:'weekly',target_aggregate_scope:C_().BorshchAggregateId,target_value_type:'retail_price',target_index_type:'wow',target_period:'2026-01-04',weight_snapshot_id:'W1',membership_snapshot_id:'M1',frontier_snapshot_id:'F1',status:'PLANNED',created_at:'2026-07-19T00:00:00Z'};Object.keys(overrides||{}).forEach(function(k){out[k]=overrides[k];});return out;}
  function frontier_(frequency,periods,dataset,scope){var items=(periods||[]).map(function(period){return{frequency:frequency||'weekly',dataset_code:dataset||'D',source_series_scope:scope||'ALL',period_start:period};});return C_().buildFrontier('F1',items);}
  function calculatorRequest_(built,frequency,indexType,period){var definition=built.definitions[0],categories=borshchMap_().map(function(x){return x.category_id;});return{contract_version:C_().Version,calculation_id:'T73_CALC',impact_items:[impact_({frequency:frequency||'weekly',source_period:period||'2026-01-04',target_period:period||'2026-01-04',target_index_type:indexType||'wow',target_value_type:definition.value_type,target_aggregate_scope:definition.aggregate_subject_id})],price_inputs:priceRows_(frequency,indexType,period,definition.value_type),aggregate_definitions:[definition],weight_snapshot:{snapshot_id:'W1',hash:'WH',rule_rows:weightRows_(categories,definition.weight_scope)},membership_snapshot:{snapshot_id:'M1',hash:'MH',rule_rows:built.membership_rows},coverage_rules:[{coverage_rule_id:'DEFAULT_COMPLETE_ONLY',allow_partial:false}],base_inputs:[]};}
  function aggregateRow_(result){var rows=(result.rows||[]).filter(function(row){return row.row_type==='AGGREGATE_RESULT';});assert_(rows.length===1,'Expected one aggregate result row.');return rows[0];}
  function planRequest_(definitions,memberships,periods,impactOverrides){var frontier=frontier_('weekly',periods);return{plan_id:'PLAN1',frontier:frontier,frontier_snapshot_id:frontier.snapshot_id,frontier_hash:frontier.hash,source_impacts:[impact_(Object.assign({source_series_scope:'ALL'},impactOverrides||{}))],definitions:definitions,membership_snapshot:{snapshot_id:'M1',hash:'MH',rule_rows:memberships},weight_snapshot:{snapshot_id:'W1',hash:'WH',rule_rows:weightRows_()},price_inputs:priceRows_(),coverage_rules:[{coverage_rule_id:'DEFAULT_COMPLETE_ONLY',allow_partial:false}],base_inputs:[],execute_calculator:false};}

  function runPure(){
    var tests=[];
    tests.push(test_('T73-001','Public exports and versions',function(){['buildDefinitions','buildBorshchDefinitions','buildAggregateMarkupDefinitions','buildDefinitionFingerprint'].forEach(function(name){assert_(typeof D_()[name]==='function');});['planRevision','planReversal','buildLatestIntents','buildPlanFingerprint'].forEach(function(name){assert_(typeof P_()[name]==='function');});assert_(D_().Release==='4.0.0-alpha.7.3'&&P_().Release==='4.0.0-alpha.7.3');return{definitions:D_().Version,planner:P_().Version};}));
    tests.push(test_('T73-002','Read-only mode metadata',function(){assert_(D_().Mode==='PURE_READ_ONLY'&&P_().Mode==='PURE_READ_ONLY_PLANNING');assert_(D_().statusSummary().physical_writes===false&&P_().statusSummary().physical_writes===false);return true;}));
    tests.push(test_('T73-003','Definition builder does not mutate inputs',function(){var input=borshchScope_(),before=JSON.stringify(input);builtBorshch_(input);assert_(JSON.stringify(input)===before);return true;}));
    tests.push(test_('T73-004','Definition ordering and fingerprint are deterministic',function(){var a=borshchScope_({dataset_codes:['D2','D1'],index_types:['yoy','wow']}),b=clone_(a);b.dataset_codes.reverse();b.index_types.reverse();var x=D_().buildBorshchDefinitions(a),y=D_().buildBorshchDefinitions(b);equal_(x.definitions,y.definitions);assert_(D_().buildDefinitionFingerprint(x)===D_().buildDefinitionFingerprint(y));return x.definitions.length;}));
    tests.push(test_('T73-005','Effective definition version resolves by target period',function(){var first=D_().Test.normalizeDefinition({definition_version:'V1',dataset_code:'D',frequency:'weekly',aggregate_level:'custom_group',aggregate_subject_id:'G',value_type:'retail_price',index_type:'wow',calculation_method:'NORMALIZED_WEIGHTED_AVERAGE',weight_rule_id:'W',membership_rule_id:'M',effective_from:'2020-01-01',effective_to:'2025-12-31'}),second=D_().Test.normalizeDefinition({definition_version:'V2',dataset_code:'D',frequency:'weekly',aggregate_level:'custom_group',aggregate_subject_id:'G',value_type:'retail_price',index_type:'wow',calculation_method:'NORMALIZED_WEIGHTED_AVERAGE',weight_rule_id:'W',membership_rule_id:'M',effective_from:'2026-01-01'});var resolved=D_().resolveDefinitionsForPeriod([first,second],'2026-02-01');assert_(resolved.length===1&&resolved[0].definition_version==='V2');return resolved[0].definition_version;}));
    tests.push(test_('T73-006','Overlapping definitions are rejected',function(){var base={definition_version:'V1',dataset_code:'D',frequency:'weekly',aggregate_level:'custom_group',aggregate_subject_id:'G',value_type:'retail_price',index_type:'wow',calculation_method:'NORMALIZED_WEIGHTED_AVERAGE',weight_rule_id:'W',membership_rule_id:'M',effective_from:'2020-01-01'};var a=D_().Test.normalizeDefinition(base),b=D_().Test.normalizeDefinition(Object.assign({},base,{definition_version:'V2',effective_from:'2025-01-01'})),failed=false;try{D_().Test.validateDefinitions([a,b]);}catch(e){failed=e.code==='ALPHA73_DEFINITION_CONFLICT';}assert_(failed);return true;}));
    tests.push(test_('T73-007','Borshch source map resolves five members',function(){var built=builtBorshch_();assert_(built.summary.active_members===5&&built.membership_rows.length===5);equal_(built.membership_rows.map(function(x){return x.category_id;}).sort(),['BEET','CABBAGE','CARROT','ONION','POTATO']);return built.summary;}));
    tests.push(test_('T73-008','Markup definition requires a valid pair',function(){var failed=false;try{D_().buildAggregateMarkupDefinitions({definition_version:'DV1',dataset_codes:['D'],frequencies:['weekly'],aggregate_subject_id:'B',weight_rule_id:'W',membership_rule_id:'M',purchase_value_type:'retail_price',retail_value_type:'retail_price',effective_from:'2020-01-01',provenance:'TEST',source_map_id:'TEST_MAP'});}catch(e){failed=e.code==='ALPHA73_MARKUP_PAIR_INVALID';}assert_(failed);return true;}));
    tests.push(test_('T73-009','One category may belong to two subjects',function(){var rows=[D_().Test.normalizeMembershipRow({membership_rule_id:'M1',membership_version:'V1',aggregate_subject_id:'A',category_id:'C'}),D_().Test.normalizeMembershipRow({membership_rule_id:'M2',membership_version:'V1',aggregate_subject_id:'B',category_id:'C'})];D_().Test.validateMembershipRows(rows);return rows.length;}));
    tests.push(test_('T73-010','Duplicate category inside subject/version is rejected',function(){var row=D_().Test.normalizeMembershipRow({membership_rule_id:'M',membership_version:'V',aggregate_subject_id:'A',category_id:'C'}),failed=false;try{D_().Test.validateMembershipRows([row,clone_(row)]);}catch(e){failed=e.code==='ALPHA73_MEMBERSHIP_DUPLICATE';}assert_(failed);return true;}));

    ['T73-011','T73-012','T73-013','T73-014','T73-015','T73-016','T73-017','T73-018'].forEach(function(id){tests.push(skip_(id,'Immutable accepted-baseline parity gate','Executed only by DEV read-only live suite against current Publish and canonical baseline.'));});
    tests.push(test_('T73-019','Explicit change remains usable when level value is missing',function(){var built=builtBorshch_(),request=calculatorRequest_(built,'weekly','wow','2026-01-04');request.price_inputs[0].current_value=null;request.price_inputs[0].current_state='MISSING';request.price_inputs[0].value_state='MISSING';request.price_inputs[0].change_pp=10;request.price_inputs[0].change_state='VALID';var row=aggregateRow_(A_().calculateBatch(request));assert_(row.applied_members_count===5);return row.aggregate_change_pp;}));
    tests.push(test_('T73-020','Split allocation and rounding remain deterministic',function(){var built=builtBorshch_(),request=calculatorRequest_(built,'weekly','wow','2026-01-04');request.membership_snapshot.rule_rows[0].allocation_factor=0.5;var a=A_().calculateBatch(request),b=A_().calculateBatch(clone_(request));assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));

    tests.push(test_('T73-021','Revision includes target period',function(){var built=builtBorshch_(),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2026-01-04']));assert_(r.revision_items.some(function(x){return x.target_period==='2026-01-04';}));return r.revision_items.length;}));
    tests.push(test_('T73-022','Weekly revision includes next existing WoW period',function(){var built=builtBorshch_(),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2026-01-04','2026-01-11']));equal_(r.revision_items.map(function(x){return x.target_period;}),['2026-01-04','2026-01-11']);return true;}));
    tests.push(test_('T73-023','Monthly revision includes next existing MoM period',function(){var built=builtBorshch_({frequencies:['monthly'],index_types:['mom']}),frontier=C_().buildFrontier('F1',[{frequency:'monthly',dataset_code:'D',source_series_scope:'ALL',period_start:'2026-01'},{frequency:'monthly',dataset_code:'D',source_series_scope:'ALL',period_start:'2026-02'}]),req=planRequest_(built.definitions,built.membership_rows,[]);req.frontier=frontier;req.frontier_snapshot_id=frontier.snapshot_id;req.frontier_hash=frontier.hash;req.source_impacts=[impact_({frequency:'monthly',source_period:'2026-01',target_period:'2026-01',target_index_type:'mom'})];var r=P_().planRevision(req);equal_(r.revision_items.map(function(x){return x.target_period;}),['2026-01','2026-02']);return true;}));
    tests.push(test_('T73-024','Revision includes next-year YoY period',function(){var built=builtBorshch_({index_types:['yoy']}),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2025-01-05','2026-01-04'],{source_period:'2025-01-05',target_index_type:'yoy'}));assert_(r.revision_items.some(function(x){return x.target_period==='2026-01-04';}));return r.revision_items.map(function(x){return x.target_period;});}));
    tests.push(test_('T73-025','December revision expands only into accepted next-year periods',function(){var built=builtBorshch_({index_types:['december']}),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2025-12-28','2026-01-04','2026-02-01'],{source_period:'2025-12-28',target_index_type:'december'}));equal_(r.revision_items.map(function(x){return x.target_period;}),['2025-12-28','2026-01-04','2026-02-01']);return true;}));
    tests.push(test_('T73-026','Multiple index types create canonical unique closure',function(){var built=builtBorshch_({index_types:['wow','yoy']}),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2025-01-05','2025-01-12','2026-01-04'],{source_period:'2025-01-05'})),keys=r.revision_items.map(function(x){return x.calculation_key;});assert_(keys.length===Object.keys(keys.reduce(function(m,k){m[k]=1;return m;},{})).length);return keys.length;}));
    tests.push(test_('T73-027','Outside-frontier candidate is audit-blocked and never batched',function(){var built=builtBorshch_(),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2026-01-04'])),blocked=r.revision_items.filter(function(x){return x.target_period==='2026-01-11'&&x.status==='BLOCKED_CONTRACT'&&x.contract_code==='ALPHA73_PERIOD_OUTSIDE_FRONTIER';}),batched=r.calculator_batches.some(function(x){return x.target_period==='2026-01-11';});assert_(blocked.length===1,'Expected one blocked outside-frontier audit item.');assert_(!batched,'Outside-frontier candidate must not create a calculator batch.');return{blocked:blocked.length,batches:r.calculator_batches.length};}));
    tests.push(test_('T73-028','Planner never creates a missing future period',function(){var built=builtBorshch_(),r=P_().planRevision(planRequest_(built.definitions,built.membership_rows,['2026-01-04']));assert_(!r.revision_items.some(function(x){return x.target_period==='2026-01-11'&&x.status==='PLANNED';}));return true;}));
    tests.push(test_('T73-029','Historical weight versions remain in supplied snapshot',function(){var rows=[{weight_rule_id:'W',weight_version:'WV1',weight_scope:'dashboard_basket',category_id:'CABBAGE',weight_value:1,effective_from:'2020-01-01',effective_to:'2025-12-31',status:'ACTIVE'},{weight_rule_id:'W',weight_version:'WV2',weight_scope:'dashboard_basket',category_id:'CABBAGE',weight_value:2,effective_from:'2026-01-01',status:'ACTIVE'}],resolved=C_().resolveVersionedRule(rows,{category_id:'CABBAGE',scope:'dashboard_basket',period:'2026-02-01'});assert_(resolved.rule.weight_version==='WV2');return resolved.rule.weight_version;}));
    tests.push(test_('T73-030','Historical membership resolves by target period',function(){var rows=[{membership_rule_id:'M',membership_version:'MV1',aggregate_subject_id:'G',category_id:'C',allocation_factor:1,include_flag:1,effective_from:'2020-01-01',effective_to:'2025-12-31',status:'ACTIVE'},{membership_rule_id:'M',membership_version:'MV2',aggregate_subject_id:'G',category_id:'C',allocation_factor:1,include_flag:1,effective_from:'2026-01-01',status:'ACTIVE'}],resolved=C_().resolveVersionedRule(rows,{category_id:'C',scope:'G',period:'2026-02-01'});assert_(resolved.rule.membership_version==='MV2');return resolved.rule.membership_version;}));
    tests.push(test_('T73-031','One-to-many expands only linked subjects',function(){var first=builtBorshch_(),second=builtBorshch_({membership_rule_id:'BORSHCH_RULE_2',membership_version:'MV2',definition_version:'DV2'});second.definitions.forEach(function(x){x.aggregate_subject_id='SECOND_SUBJECT';x.aggregate_series_key='SECOND_'+x.aggregate_series_key;});second.membership_rows.forEach(function(x){x.aggregate_subject_id='SECOND_SUBJECT';x.membership_rule_id='BORSHCH_RULE_2';});var r=P_().planRevision(planRequest_(first.definitions.concat(second.definitions),first.membership_rows.concat(second.membership_rows),['2026-01-04'])),planned=r.revision_items.filter(function(x){return x.target_period==='2026-01-04'&&x.status==='PLANNED';});assert_(planned.length===2);return planned.map(function(x){return x.aggregate_subject_id;}).sort();}));
    tests.push(test_('T73-032','Duplicate source impacts preserve lineage without duplicate rows',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04']);req.source_impacts.push(impact_({load_id:'L2',operation_id:'O2'}));var r=P_().planRevision(req),target=r.revision_items.filter(function(x){return x.target_period==='2026-01-04'&&x.status==='PLANNED';});assert_(target.length===1&&target[0].source_impacts.length===2);return target[0].source_impacts;}));

    tests.push(test_('T73-033','Reversal uses revision dependency contract',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04','2026-01-11']);req.previous_price_inputs=req.price_inputs;req.has_current_effect=true;req.current_effect_evidence={load_id:'L1',accepted_rows:1};var r=P_().planReversal(req);assert_(r.reversal_items.length===2);return r.reversal_items.length;}));
    tests.push(test_('T73-034','Reversal uses previous accepted inputs',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04']);req.previous_price_inputs=priceRows_('weekly','wow','2026-01-04','retail_price',[1,1,1,1,1]);req.execute_calculator=true;req.has_current_effect=true;req.current_effect_evidence={load_id:'L1',accepted_rows:1};var r=P_().planReversal(req);assert_(r.planned_rows.length>0);return r.planned_rows.length;}));
    tests.push(test_('T73-035','Non-current reversal returns NO_CURRENT_EFFECT',function(){var r=P_().planReversal({has_current_effect:false,source_impacts:[impact_()]});assert_(r.status==='NO_CURRENT_EFFECT'&&r.planned_rows.length===0);return r.status;}));
    tests.push(test_('T73-036','New maximum creates latest intent',function(){var r=P_().buildLatestIntents([{aggregate_series_key:'S',aggregate_row_key:'R2',frequency:'weekly',period_start:'2026-01-11'}],{rows:[{aggregate_series_key:'S',aggregate_row_key:'R1',frequency:'weekly',period_start:'2026-01-04',is_latest_period:1}]});assert_(r.intents.length===1&&r.intents[0].next_latest_row_key==='R2');return r.intents[0];}));
    tests.push(test_('T73-037','Non-maximum revision does not change latest',function(){var r=P_().buildLatestIntents([{aggregate_series_key:'S',aggregate_row_key:'R0',frequency:'weekly',period_start:'2025-12-28'}],{rows:[{aggregate_series_key:'S',aggregate_row_key:'R1',frequency:'weekly',period_start:'2026-01-04',is_latest_period:1}]});assert_(r.intents.length===0);return true;}));
    tests.push(test_('T73-038','Reversal of maximum selects previous existing period',function(){var r=P_().buildLatestIntents([],{rows:[{aggregate_series_key:'S',aggregate_row_key:'R1',frequency:'weekly',period_start:'2026-01-04'},{aggregate_series_key:'S',aggregate_row_key:'R2',frequency:'weekly',period_start:'2026-01-11',is_latest_period:1}],excluded_row_keys:['R2']});assert_(r.intents[0].next_latest_row_key==='R1');return r.intents[0];}));
    tests.push(test_('T73-039','Tied latest identity is blocked',function(){var r=P_().buildLatestIntents([{aggregate_series_key:'S',aggregate_row_key:'R0',frequency:'weekly',period_start:'2025-12-28'}],{rows:[{aggregate_series_key:'S',aggregate_row_key:'R1',frequency:'weekly',period_start:'2026-01-04'},{aggregate_series_key:'S',aggregate_row_key:'R2',frequency:'weekly',period_start:'2026-01-04'}]});assert_(r.conflicts.length===1&&r.conflicts[0].code==='ALPHA73_LATEST_CONFLICT');return r.conflicts[0];}));
    tests.push(test_('T73-040','Latest intents are deterministic after shuffle',function(){var rows=[{aggregate_series_key:'S',aggregate_row_key:'R1',frequency:'weekly',period_start:'2026-01-04',is_latest_period:1},{aggregate_series_key:'S',aggregate_row_key:'R2',frequency:'weekly',period_start:'2026-01-11'}],a=P_().buildLatestIntents([], {rows:rows}),b=P_().buildLatestIntents([], {rows:rows.slice().reverse()});assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));

    tests.push(test_('T73-041','Shuffled inputs give identical plan fingerprint',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04','2026-01-11']),a=P_().planRevision(req),b=clone_(req);b.definitions.reverse();b.membership_snapshot.rule_rows.reverse();b.frontier.keys=Object.keys(b.frontier.keys).reverse().reduce(function(m,k){m[k]=true;return m;},{});b=P_().planRevision(b);assert_(a.fingerprint===b.fingerprint);return a.fingerprint;}));
    tests.push(test_('T73-042','Plan fingerprint ignores runtime metadata',function(){var base={status:'SUCCESS',plan_id:'P',revision_items:[{a:1}],created_at:'A',elapsed_ms:1},other=clone_(base);other.created_at='B';other.elapsed_ms=999;assert_(P_().buildPlanFingerprint(base)===P_().buildPlanFingerprint(other));return true;}));
    tests.push(test_('T73-043','Planner does not mutate request',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04']),before=JSON.stringify(req);P_().planRevision(req);assert_(JSON.stringify(req)===before);return true;}));
    tests.push(test_('T73-044','Runtime status confirms no writes',function(){assert_(D_().statusSummary().physical_writes===false&&P_().statusSummary().physical_writes===false);return{definitions:D_().statusSummary(),planner:P_().statusSummary()};}));
    tests.push(test_('T73-045','Planner inspection metrics are linear counters',function(){var built=builtBorshch_(),req=planRequest_(built.definitions,built.membership_rows,['2026-01-04','2026-01-11']),r=P_().planRevision(req),m=r.summary.metrics;assert_(m.source_impacts_inspected===1&&m.definition_rows_indexed===built.definitions.length&&m.definition_index_builds===1&&m.membership_index_builds===1&&m.frontier_index_builds===1&&m.calculation_batches===2);return m;}));
    tests.push(test_('T73-046','Frozen Alpha.7.1 and Alpha.7.2 contracts are exact',function(){assert_(C_().Version==='4.0-aggregate-contract-2');assert_(A_().Version==='4.0-aggregate-calculator-1');return{contract:C_().Version,calculator:A_().Version};}));
    tests.push(skip_('T73-047','Pre/post accepted baseline inventory','Requires DEV read-only live suite.'));
    tests.push(skip_('T73-048','Installer apply/full-test/rollback','Executed by package shell self-test and operator installation.'));

    var failed=tests.filter(function(t){return t.status==='FAIL';}),skipped=tests.filter(function(t){return t.status==='SKIP';});
    return{suite:'ALPHA73_SPECIAL_REVISION_PURE',release:'4.0.0-alpha.7.3',total:tests.length,passed:tests.length-failed.length-skipped.length,failed:failed.length,skipped:skipped.length,status:failed.length?'FAILED':'SUCCESS',tests:tests};
  }

  var LIVE_EVIDENCE_CACHE = null;
  function normLive_(value){return text_(value).toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ');}
  function readAcceptedSubset_(spreadsheetId){
    var spreadsheet=SpreadsheetApp.openById(spreadsheetId),sheet=spreadsheet.getSheetByName(C_().AggregateSheet),lastRow=sheet.getLastRow(),lastColumn=sheet.getLastColumn(),headers=sheet.getRange(1,1,1,lastColumn).getValues()[0],index={};
    headers.forEach(function(header,i){index[text_(header)]=i;});
    ['frequency','aggregate_level','aggregate_name','value_type','index_type','period_start','coverage_categories_count','aggregate_change_pp','aggregate_value','aggregate_base_value'].forEach(function(header){assert_(index[header]!==undefined,'Live baseline missing '+header);});
    var out={borshch:{},markup:{weekly:[],monthly:[]}},chunk=1500;
    for(var start=2;start<=lastRow;start+=chunk){var count=Math.min(chunk,lastRow-start+1),values=sheet.getRange(start,1,count,lastColumn).getValues();values.forEach(function(row){var frequency=normLive_(row[index.frequency]),level=normLive_(row[index.aggregate_level]),name=normLive_(row[index.aggregate_name]),valueType=normLive_(row[index.value_type]),indexType=normLive_(row[index.index_type]);if(level==='custom_group'&&name.indexOf('борщ')>=0){var key=frequency+'|'+indexType;out.borshch[key]=out.borshch[key]||[];out.borshch[key].push(row);}if((valueType.indexOf('нацен')>=0||valueType.indexOf('markup')>=0)&&(frequency==='weekly'||frequency==='monthly')&&level!=='category'){out.markup[frequency].push(row);}});}
    Object.keys(out.borshch).forEach(function(key){out.borshch[key].sort(function(a,b){return JSON.stringify(a)<JSON.stringify(b)?-1:1;});});
    ['weekly','monthly'].forEach(function(key){out.markup[key].sort(function(a,b){return JSON.stringify(a)<JSON.stringify(b)?-1:1;});});
    return{spreadsheet_name:spreadsheet.getName(),headers:headers,index:index,borshch:out.borshch,markup:out.markup};
  }
  function liveEvidence_(){
    if(LIVE_EVIDENCE_CACHE)return LIVE_EVIDENCE_CACHE;
    var config=AKORT.Config.load({includeSystemSettings:false}),resources=config&&config.resources||{},currentId=resources.publishSpreadsheetId,baselineId=resources.alpha71BaselinePublishSpreadsheetId;
    assert_(currentId&&baselineId,'DEV Publish and immutable baseline IDs must be configured.');
    LIVE_EVIDENCE_CACHE={current:readAcceptedSubset_(currentId),baseline:readAcceptedSubset_(baselineId)};return LIVE_EVIDENCE_CACHE;
  }
  function assertSubsetEqual_(actual,expected,label){assert_(actual.length>0,label+' subset is empty.');equal_(actual,expected,label+' differs from immutable accepted baseline.');return{rows:actual.length,hash:C_().Test.hash(JSON.stringify(actual))};}
  function liveBorshchGate_(frequency,indexType){var evidence=liveEvidence_(),key=frequency+'|'+indexType,actual=evidence.current.borshch[key]||[],expected=evidence.baseline.borshch[key]||[],result=assertSubsetEqual_(actual,expected,'Borshch '+key);var idx=evidence.current.index.coverage_categories_count;actual.forEach(function(row){var coverage=Number(row[idx]);assert_(isFinite(coverage)&&Math.floor(coverage)===coverage&&coverage>=1&&coverage<=5,'Borshch accepted coverage must be an integer from one to five categories.');});return result;}
  function liveMarkupGate_(frequency){var evidence=liveEvidence_(),actual=evidence.current.markup[frequency]||[],expected=evidence.baseline.markup[frequency]||[],result=assertSubsetEqual_(actual,expected,'Aggregate markup '+frequency),idx=evidence.current.index;actual.forEach(function(row){var value=Number(row[idx.aggregate_value]),base=Number(row[idx.aggregate_base_value]),change=Number(row[idx.aggregate_change_pp]);if(isFinite(value)&&isFinite(base)&&isFinite(change))stored6Approx_(change,value-base,'Markup arithmetic mismatch.');});return result;}

  function runLive(){
    return AKORT.Core.safeRun('ALPHA73_READ_ONLY_LIVE',function(){
      AKORT.EnvironmentGuard.assertDev();
      var pure=runPure(),tests=pure.tests.filter(function(t){return ['T73-011','T73-012','T73-013','T73-014','T73-015','T73-016','T73-017','T73-018','T73-047','T73-048'].indexOf(t.id)<0;}),before=C_().inventory(),baseline=C_().baselineInventory();
      tests.push(test_('T73-011','Accepted weekly Borshch WoW parity',function(){return liveBorshchGate_('weekly','wow');}));
      tests.push(test_('T73-012','Accepted weekly Borshch YoY parity',function(){return liveBorshchGate_('weekly','yoy');}));
      tests.push(test_('T73-013','Accepted weekly Borshch December parity',function(){return liveBorshchGate_('weekly','december');}));
      tests.push(test_('T73-014','Accepted monthly Borshch MoM parity',function(){return liveBorshchGate_('monthly','mom');}));
      tests.push(test_('T73-015','Accepted monthly Borshch YoY parity',function(){return liveBorshchGate_('monthly','yoy');}));
      tests.push(test_('T73-016','Accepted monthly Borshch December parity',function(){return liveBorshchGate_('monthly','december');}));
      tests.push(test_('T73-017','Accepted weekly aggregate-markup parity',function(){return liveMarkupGate_('weekly');}));
      tests.push(test_('T73-018','Accepted monthly aggregate-markup parity',function(){return liveMarkupGate_('monthly');}));
      tests.push(test_('T73-047','Pre/post accepted baseline inventory',function(){var comparison=C_().compareInventory(before,baseline);assert_(comparison.equal);assert_(before.rows===61636&&before.columns===29);assert_(before.data_hash==='1a6db3d0e56560cc908493fc3ced738d609cdb278bab5390764f090a52efd3f5');assert_(before.fingerprint==='459441b75a8020c361d8c2d5a16cb61293322b49e3c1483929cdf3ee3083624a');var after=C_().inventory();assert_(before.data_hash===after.data_hash&&before.fingerprint===after.fingerprint);return{comparison:comparison,before:before,after:after};}));
      tests.push(skip_('T73-048','Installer apply/full-test/rollback','External package evidence; verify INSTALLATION_REPORT.json before acceptance.'));
      tests.sort(function(a,b){return a.id<b.id?-1:a.id>b.id?1:0;});
      var failed=tests.filter(function(t){return t.status==='FAIL';}),skipped=tests.filter(function(t){return t.status==='SKIP';}),report={suite:'ALPHA73_READ_ONLY_LIVE_R4',total:tests.length,passed:tests.length-failed.length-skipped.length,failed:failed.length,skipped:skipped.length,status:failed.length?'FAILED':'SUCCESS',tests:tests};
      return failed.length?AKORT.Result.failure('ALPHA73_TESTS_FAILED','Alpha.7.3 accepted read-only suite failed.',report):AKORT.Result.success('Alpha.7.3 accepted read-only gates passed; physical writes remain disabled.',report);
    },{lock:false,persistLogs:false});
  }

  function status(){return{release:'4.0.0-alpha.7.3',definition_version:D_().Version,planner_version:P_().Version,test_ids:'T73-001..T73-048',mode:'PURE_STATIC_READ_ONLY',physical_writes:false,acceptance_status:'ACCEPTED_AND_CLOSED'};}
  return Object.freeze({runPure:runPure,runLive:runLive,status:status});
})();

function AKORT_alpha73PureProbe(){var report=AKORT.Alpha73Tests.runPure(),result=report.failed?AKORT.Result.failure('ALPHA73_PURE_TESTS_FAILED','Alpha.7.3 pure tests failed.',report):AKORT.Result.success('Alpha.7.3 pure tests passed.',report);console.log(JSON.stringify({ok:result.ok,status:result.status,total:report.total,passed:report.passed,failed:report.failed,skipped:report.skipped},null,2));return result;}
function AKORT_alpha73RunTests(){var result=AKORT.Alpha73Tests.runLive(),data=result&&(result.data||result.details)||{};console.log(JSON.stringify({ok:result.ok,status:result.status,total:data.total,passed:data.passed,failed:data.failed,skipped:data.skipped},null,2));return result;}
function AKORT_alpha73Status(){var data=AKORT.Alpha73Tests.status(),result=AKORT.Result.success('Alpha.7.3 accepted status loaded.',data);console.log(JSON.stringify(result,null,2));return result;}
